---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: matter-server
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m
  values:
    controllers:
      matter-server:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"multus-iot",
                "namespace": "network",
                "ips": ["10.40.0.101/16"],
                "mac": "3e:59:e4:f7:43:11"
              }]
          securityContext:
            runAsUser: 0 # Must be run as root user
            runAsGroup: 0
            runAsNonRoot: false # Must be run as root user
            fsGroup: 0
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 34
        containers:
          app:
            image:
              repository: ghcr.io/home-assistant-libs/python-matter-server
              tag: 7.0.1
            env:
              MATTER_SERVER__INSTANCE_NAME: matter-server
              MATTER_SERVER__PORT: &wsPort 5580
              MATTER_SERVER__APPLICATION_URL: &host matter.${SECRET_DOMAIN}
              MATTER_SERVER__LOG_LEVEL: debug
    service:
      matter-server:
        controller: matter-server
        ports:
          ws:
            port: *wsPort
    ingress:
      internal:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
          nginx.org/websocket-services: matter-server
        hosts:
          - host: *host
            paths:
              - path: /
                service:
                  identifier: matter-server
                  port: *wsPort
    persistence:
      data:
        existingClaim: ${VOLSYNC_CLAIM}
