---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres17
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2-22@sha256:2997c8a5b4daefa9762b872371546a4aba145f486c21a8ad8dabb15ac4bc6f8d
  instances: 3
  # - unsupervised: automated update of the primary once all
  #                 replicas have been upgraded (default)
  # - supervised: requires manual supervision to perform
  #               the switchover of the primary
  primaryUpdateStrategy: unsupervised
  
  # Storage configuration
  storage:
    size: 20Gi
    storageClass: ceph-block

  # Superuser configuration
  superuserSecret:
    name: cloudnative-pg-secret
  enableSuperuserAccess: true

  # Note: previousCluster needs to be set to the name of the previous
  # cluster when recovering from an existing cnpg cluster
  bootstrap:
    recovery:
      source: &previousCluster postgres17-v2

  # Configuration of the PostgreSQL server
  postgresql:
    parameters:
      max_connections: "250"
      shared_buffers: 128MB
  
  # Pod affinity Rules
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
    nodeSelector:
      kubernetes.io/os: linux

  # Pod resource boundaries
  resources:
    requests:
      cpu: 500m
    limits:
      hugepages-2Mi: 2Gi # Requires sysctl set on the host
      memory: 4Gi

  # Prometheus Exporter
  monitoring:
    enablePodMonitor: true
    # https://github.com/cloudnative-pg/cloudnative-pg/issues/2501
    podMonitorMetricRelabelings:
      - { sourceLabels: [ "cluster" ], targetLabel: cnpg_cluster, action: replace }
      - { regex: cluster, action: labeldrop }

  # Backup Configuration  
  backup:
    retentionPolicy: 30d
    barmanObjectStore: &barmanObjectStore
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 4
      destinationPath: s3://cloudnative-pg/
      endpointURL: https://604128bd389364580b3208006c949072.r2.cloudflarestorage.com
      # Note: serverName version needs to be incremented
      # when recovering from an existing cnpg cluster
      serverName: &currentCluster postgres17-v4
      s3Credentials:
        accessKeyId:
          name: cloudnative-pg-secret
          key: aws-access-key-id
        secretAccessKey:
          name: cloudnative-pg-secret
          key: aws-secret-access-key


  # Note: externalClusters is needed when recovering from an existing cnpg cluster
  externalClusters:
    - name: *previousCluster 
      barmanObjectStore:
        <<: *barmanObjectStore
        serverName: *previousCluster
