---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
components:
  - ../../components/alerts
  - ../../components/namespace
  - ../../components/global-vars
  - ../../components/sops
resources:
  - ./cilium/ks.yaml
  # - ./coredns/ks.yaml
  # - ./metrics-server/ks.yaml
  # - ./reloader/ks.yaml
  # - ./kubelet-csr-approver/ks.yaml
  # - ./spegel/ks.yaml
  # - ./descheduler/ks.yaml
