---
# yaml-language-server: $schema=https://raw.githubusercontent.com/k8snetworkplumbingwg/network-attachment-definition-client/refs/tags/v1.7.5/artifacts/networks-crd.yaml
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: multus-iot
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "multus-iot",
      "plugins": [
        {
          "type": "macvlan",
          "master": "eth0.40",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": [
              {"dst": "10.40.0.0/16", "gw": "10.40.0.1"}
            ]
          }
        }
      ]
    }
