---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.2.0/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      redis:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: public.ecr.aws/docker/library/redis
              tag: 7.4.2
            command:
              - sh
            args:
              - -c
              - >-
                redis-server --requirepass $REDIS_PASSWORD
            env:
              REDIS_REPLICATION_MODE: master
              REDIS_PORT: "6379"
              REDIS_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: "redis-secret"
                    key: REDIS_PASSWORD
            resources:
              requests:
                cpu: 10m
                memory: 10Mi
              limits:
                memory: 100Mi
    service:
      main:
        controller: redis
        ports:
          redis:
            enabled: true
            port: 6379
