{
 "title": "Netdata and prometheus",
 "description": "Updated Netdata dashboards for Grafana via Prometheus. ",
 "tags": [
  "netdata",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(netdata_info{instance=\"nas.sklab.dev\"},instance)"
    }
   },
   {
    "name": "view",
    "label": "View",
    "query": "metrics(netdata_.+_cpu_cpu_time___average)"
   },
   {
    "name": "port",
    "label": "port",
    "query": "label_values(netdata_system_uptime_seconds_average, instance)"
   },
   {
    "name": "cpu",
    "label": "cpu",
    "query": "netdata_cpu_softnet_stat_events_persec_average"
   }
  ]
 },
 "panels": [
  {
   "title": "Basic CPU / Mem / Disk Gauge",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Busy",
     "type": "gauge",
     "description": "Busy state of all CPU cores together",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(netdata_system_cpu_percentage_average{dimension!=\"idle\",instance=\"$instance\"})"
      }
     ]
    },
    {
     "title": "Used RAM Memory",
     "type": "gauge",
     "description": "Non available RAM memory",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(netdata_system_ram_MiB_average{dimension=\"used\",instance=\"$instance\"}) by (instance) / (sum(netdata_system_ram_MiB_average{instance=\"$instance\"}) by (instance)) * 100"
      }
     ]
    },
    {
     "title": "Used SWAP",
     "type": "gauge",
     "description": "Used Swap",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(netdata_system_swap_MiB_average{dimension=\"used\",instance=\"$instance\"}) by (instance) / sum(netdata_system_swap_MiB_average{instance=\"$instance\"}) by (instance) * 100"
      }
     ]
    },
    {
     "title": "Used Root FS",
     "type": "gauge",
     "description": "Used Root FS",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(netdata_disk_space_GiB_average{instance=\"$instance\",family=\"/\",dimension=\"used\"}) by (instance) / sum(netdata_disk_space_GiB_average{instance=\"$instance\",family=\"/\"}) by (instance) * 100"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "description": "System uptime",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "netdata_system_uptime_seconds_average{instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "stat",
     "description": "Total number of CPU cores",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(netdata_cpu_cpu_percentage_average{instance=\"$instance\",dimension=\"idle\"})"
      }
     ]
    },
    {
     "title": "Total RAM",
     "type": "stat",
     "description": "Total RAM",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(netdata_system_ram_MiB_average{instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Total SWAP",
     "type": "stat",
     "description": "Total SWAP",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(netdata_system_swap_MiB_average{instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Total RootFS",
     "type": "stat",
     "description": "Total RootFS",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(netdata_disk_space_GiB_average{instance=~\"$instance\",family=\"/\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "System overview: CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total CPU utilization",
     "type": "graph",
     "description": "Total CPU utilization (all cores). 100% here means there is no CPU idle time at all. You can get per core usage at the _CPUs_ section and per application usage at the _Applications monitoring_ section.\n\nKeep an eye on **iowait**. If it is constantly high, your disks are a bottleneck and they slow your system down.\n\nAn important metric worth monitoring, is **softirq**. A constantly high percentage of softirq may indicate network driver issues.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "netdata_system_cpu_percentage_average{dimension!~\"idle\",instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System overview: load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "System load average",
     "type": "graph",
     "description": "Current system load, i.e. the number of processes using CPU or waiting for system resources (usually CPU and disk). The 3 metrics refer to 1, 5 and 15 minute averages. The system calculates this once every 5 seconds.\n\nFor more information check this [Wikipedia article](https://en.wikipedia.org/wiki/Load_(computing))",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "netdata_system_load_load_average{dimension!=\"load15\",instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      },
      {
       "expr": "netdata_system_load_load_average{dimension=\"load15\",instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System overview: disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk I/O",
     "type": "graph",
     "description": "Total Disk I/O, for all physical disks. You can get detailed information about each disk at the _Disks_ section and per application Disk usage at the _Applications Monitoring_ section.\n\nPhysical are all the disks that are listed in `/sys/block`, but do not exist in `/sys/devices/virtual/block`.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "expr": "netdata_system_io_KiB_persec_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Memory paged from/to disk",
     "type": "graph",
     "description": "Memory paged from/to disk. This is usually the total disk I/O of the system.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "expr": "netdata_system_pgpgio_KiB_persec_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System overview: RAM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "System RAM",
     "type": "graph",
     "description": "System Random Access Memory (i.e. physical memory) usage.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "netdata_system_ram_MiB_average{dimension!=\"free\",instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      },
      {
       "expr": "netdata_system_ram_MiB_average{dimension=\"free\",instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System overview: swap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "System swap",
     "type": "graph",
     "description": "System swap memory usage. Swap space is used when the amount of physical memory (RAM) is full. When the system needs more memory resources and the RAM is full, inactive pages in memory are moved to the swap space (usually a disk, a disk partition or a file).",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "netdata_system_swap_MiB_average{dimension=\"free\",instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      },
      {
       "expr": "netdata_system_swap_MiB_average{dimension!=\"free\",instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Swap I/O - No data collected",
     "type": "graph",
     "description": "Total Swap I/O. (netdata measures both `in` and `out`. If either of them is not shown in the chart, it is because it is zero - you can change the page settings to always render all the available dimensions on all charts).",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "netdata_system_swapio_KiB_persec_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System overview: network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "IPv4 bandwidth",
     "type": "graph",
     "description": "Total IPv4 Traffic.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "netdata_system_ip_kilobits_persec_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv6 bandwidth",
     "type": "graph",
     "description": "Total IPv6 Traffic.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "netdata_system_ipv6_kilobits_persec_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System overview: processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "System processes",
     "type": "graph",
     "description": "System processes. **Running** are the processes in the CPU. **Blocked** are processes that are willing to enter the CPU, but they cannot, e.g. because they wait for disk activity.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "netdata_system_processes_processes_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Started processes",
     "type": "graph",
     "description": "Number of new processes created.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "netdata_system_forks_processes_persec_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "System active processes",
     "type": "graph",
     "description": "All system processes.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1903 },
     "targets": [
      {
       "expr": "netdata_system_active_processes_processes_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "CPU context switches",
     "type": "graph",
     "description": "[Context Switches](https://en.wikipedia.org/wiki/Context_switch), is the switching of the CPU from one process, task or thread to another. If there are many processes or threads willing to execute and very few CPU cores available to handle them, the system is making more context switching to balance the CPU resources among them. The whole process is computationally intensive. The more the context switches, the slower the system gets.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1903 },
     "targets": [
      {
       "expr": "netdata_system_ctxt_context_switches_persec_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System overview: idle jitter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU idle jitter",
     "type": "graph",
     "description": "Idle jitter is calculated by netdata. A thread is spawned that requests to sleep for a few microseconds. When the system wakes it up, it measures how many microseconds have passed. The difference between the requested and the actual duration of the sleep, is the idle jitter. This number is useful in real-time environments, where CPU jitter can affect the quality of the service (like VoIP media gateways).",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "netdata_system_idlejitter_microseconds_lost_persec_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System overview: interrupts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU interrupts",
     "type": "graph",
     "description": "Total number of CPU interrupts. Check the system interrupts graph that gives more detail about each interrupt and also the _CPUs_ section where interrupts are analyzed per CPU core.",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "netdata_system_intr_interrupts_persec_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "System interrupts",
     "type": "graph",
     "description": "CPU interrupts in detail. At the _CPUs_ section, interrupts are analyzed per CPU core.",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 36 },
     "targets": [
      {
       "expr": "netdata_system_interrupts_interrupts_persec_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System overview: softirqs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "System softirqs",
     "type": "graph",
     "description": "CPU softirqs in detail. At the _CPUs_ section, softirqs are analyzed per CPU core.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "netdata_system_softirqs_softirqs_persec_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System overview: softnet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "System softnet_stat",
     "type": "graph",
     "description": "Statistics for CPUs SoftIRQs related to network receive work.\n\nBreak down per CPU core can be found at _CPU / softnet statistics_. processed states the number of packets processed, dropped is the number packets dropped because the network device backlog was full (to fix them on Linux use `sysctl` to increase `net.core.netdev_max_backlog`), squeezed is the number of packets dropped because the network device budget ran out (to fix them on Linux use `sysctl` to increase `net.core.netdev_budget`).\n\nMore information about identifying and troubleshooting network driver related issues can be found at [Red Hat Enterprise Linux Network Performance Tuning Guide](https://access.redhat.com/sites/default/files/attachments/20150325_network_performance_tuning.pdf).",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "netdata_system_softnet_stat_events_persec_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System overview: entropy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Available entropy",
     "type": "graph",
     "description": "[Entropy](https://en.wikipedia.org/wiki/Entropy_(computing)), is a pool of random numbers ([/dev/random](https://en.wikipedia.org/wiki//dev/random)) that is mainly used in cryptography.\n\nIf the pool of entropy gets empty, processes requiring random numbers may run a lot slower (it depends on the interface each program uses), waiting for the pool to be replenished. Ideally a system with high entropy demands should have a hardware device for that purpose (TPM is one such device).\n\nThere are also several software-only options you may install, like `haveged`, although these are generally useful only in servers.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "none", "label": "entropy" }
     ],
     "targets": [
      {
       "expr": "netdata_system_entropy_entropy_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System overview: IPC semaphores",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "IPC semaphore arrays",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "netdata_system_ipc_semaphore_arrays_arrays_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPC semaphores",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "targets": [
      {
       "expr": "netdata_system_ipc_semaphores_semaphores_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPUs details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU interrupts ($cpu)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
     "repeat": "cpu",
     "targets": [
      {
       "expr": "netdata_cpu_interrupts_interrupts_persec_average{chart=~\"cpu.[[cpu]]_interrupts\",instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "CPU softirqs ($cpu)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
     "repeat": "cpu",
     "targets": [
      {
       "expr": "netdata_cpu_softirqs_softirqs_persec_average{chart=~\"cpu.[[cpu]]_softirqs\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Core thermal throttling events",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "short", "label": "events/s" }
     ],
     "targets": [
      {
       "expr": "netdata_cpu_core_throttling_events_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPUs: softnet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU softnet_stat ($cpu)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1904 },
     "repeat": "cpu",
     "targets": [
      {
       "expr": "netdata_cpu_softnet_stat_events_persec_average{chart=~\"cpu.[[cpu]]_softnet_stat\",instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "CPU clock",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1911 },
     "yaxes": [
      { "format": "none", "label": "Mhz" }
     ],
     "targets": [
      {
       "expr": "netdata_cpufreq_cpufreq_MHz_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory: system",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Available RAM for applications",
     "type": "graph",
     "description": "Available Memory is estimated by the kernel, as the amount of RAM that can be used by userspace processes, without causing swapping.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2798 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "netdata_mem_available_MiB_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Committed (allocated) memory",
     "type": "graph",
     "description": "Committed Memory, is the sum of all memory which has been allocated by processes.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2798 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "netdata_mem_committed_MiB_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Memory page faults",
     "type": "graph",
     "description": "A [page fault](https://en.wikipedia.org/wiki/Page_fault) is a type of interrupt, called trap, raised by computer hardware when a running program accesses a memory page that is mapped into the virtual address space, but not actually loaded into main memory.\n\nIf the page is loaded in memory at the time the fault is generated, but is not marked in the memory management unit as being loaded in memory, then it is called a minor or soft page fault.\n\nA major page fault is generated when the system needs to load the memory page from disk or swap memory.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2838 },
     "yaxes": [
      { "format": "none", "label": "page faults" }
     ],
     "targets": [
      {
       "expr": "netdata_mem_pgfaults_faults_persec_average{dimension=\"minor\",instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      },
      {
       "expr": "netdata_mem_pgfaults_faults_persec_average{dimension=\"major\",instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory: kernel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Writeback memory",
     "type": "graph",
     "description": "**Dirty** is the amount of memory waiting to be written to disk. **Writeback** is how much memory is actively being written to disk.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2799 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "netdata_mem_writeback_MiB_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Memory used by kernel",
     "type": "graph",
     "description": "The total amount of memory being used by the kernel. **Slab** is the amount of memory used by the kernel to cache data structures for its own use. **KernelStack** is the amount of memory allocated for each task done by the kernel. **PageTables** is the amount of memory decicated to the lowest level of page tables (A page table is used to turn a virtual address into a physical memory address). **VmallocUsed** is the amount of memory being used as virtual address space.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2799 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "netdata_mem_kernel_MiB_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory: slab",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reclaimable kernel memory",
     "type": "graph",
     "description": "**Reclaimable** is the amount of memory which the kernel can reuse. **Unreclaimable** can not be reused even when the kernel is lacking memory.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3322 },
     "targets": [
      {
       "expr": "netdata_mem_slab_MiB_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disks:",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "repeat": "disk",
   "collapsed": true,
   "panels": [
    {
     "title": "Disk I/O bandwidth",
     "type": "graph",
     "description": "Amount of data transferred to and from disk.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3323 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "netdata_disk_io_KiB_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{family}} {{dimension}}"
      }
     ]
    },
    {
     "title": "Disk completed I/O operations",
     "type": "graph",
     "description": "Completed disk I/O operations. Keep in mind the number of operations requested might be higher, since the system is able to merge adjacent to each other (see merged operations chart).",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3323 },
     "yaxes": [
      { "format": "none", "label": "operations/s" }
     ],
     "targets": [
      {
       "expr": "netdata_disk_ops_operations_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{family}} {{dimension}}"
      }
     ]
    },
    {
     "title": "Disk current I/O operations",
     "type": "graph",
     "description": "I/O operations currently in progress. This metric is a snapshot - it is not an average over the last interval.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3330 },
     "yaxes": [
      { "format": "none", "label": "operations" }
     ],
     "targets": [
      {
       "expr": "netdata_disk_ops_operations_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{family}} {{dimension}}"
      }
     ]
    },
    {
     "title": "Disk backlog",
     "type": "graph",
     "description": "Backlog is an indication of the duration of pending disk operations. On every I/O event the system is multiplying the time spent doing I/O since the last update of this field with the number of pending operations. While not accurate, this metric can provide an indication of the expected completion time of the operations in progress.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3330 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "netdata_disk_backlog_milliseconds_average{instance=~\"$instance\"}",
       "legendFormat": "{{family}} {{dimension}}"
      }
     ]
    },
    {
     "title": "Disk utilization time",
     "type": "graph",
     "description": "Disk Utilization measures the amount of time the disk was busy with something. This is not related to its performance. 100% means that the system always had an outstanding operation on the disk.\n\nKeep in mind that depending on the underlying technology of the disk, 100% here may or may not be an indication of congestion.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3337 },
     "yaxes": [
      { "format": "percent", "label": "% of time working" }
     ],
     "targets": [
      {
       "expr": "netdata_disk_util___of_time_working_average{instance=~\"$instance\"}",
       "legendFormat": "{{family}} {{dimension}}"
      }
     ]
    },
    {
     "title": "Average completed I/O operation time",
     "type": "graph",
     "description": "The average time for I/O requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3337 },
     "yaxes": [
      { "format": "ms", "label": "ms per operation" }
     ],
     "targets": [
      {
       "expr": "netdata_disk_await_milliseconds_operation_average{instance=~\"$instance\"}",
       "legendFormat": "{{family}} {{dimension}}"
      }
     ]
    },
    {
     "title": "Average completed I/O operation bandwidth",
     "type": "graph",
     "description": "The average I/O operation size.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3344 },
     "yaxes": [
      { "format": "deckbytes", "label": "kilobytes per operation" }
     ],
     "targets": [
      {
       "expr": "netdata_disk_avgsz_KiB_operation_average{instance=~\"$instance\"}",
       "legendFormat": "{{family}} {{dimension}}"
      }
     ]
    },
    {
     "title": "Average service time",
     "type": "graph",
     "description": "The average service time for completed I/O operations. This metric is calculated using the total busy time of the disk and the number of completed operations. If the disk is able to execute multiple parallel operations the reporting average service time will be misleading.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3344 },
     "yaxes": [
      { "format": "ms", "label": "ms per operation" }
     ],
     "targets": [
      {
       "expr": "netdata_disk_svctm_milliseconds_operation_average{instance=~\"$instance\"}",
       "legendFormat": "{{family}} {{dimension}}"
      }
     ]
    },
    {
     "title": "Disk merged operations",
     "type": "graph",
     "description": "The number of merged disk operations. The system is able to merge adjacent I/O operations, for example two 4KB reads can become one 8KB read before given to disk.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3351 },
     "targets": [
      {
       "expr": "netdata_disk_mops_merged_operations_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{family}} {{dimension}}"
      }
     ]
    },
    {
     "title": "Disk total I/O time",
     "type": "graph",
     "description": "The sum of the duration of all completed I/O operations. This number can exceed the interval if the disk is able to execute I/O operations in parallel.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3351 },
     "targets": [
      {
       "expr": "netdata_disk_iotime_milliseconds_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{family}} {{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disks: filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "repeat": "fs",
   "collapsed": true,
   "panels": [
    {
     "title": "Disk space usage",
     "type": "graph",
     "description": "Disk space utilization. reserved for root is automatically reserved by the system to prevent the root user from getting out of space.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3526 },
     "targets": [
      {
       "expr": "netdata_disk_space_GiB_average{instance=~\"$instance\"}",
       "legendFormat": "{{family}} {{dimension}}"
      }
     ]
    },
    {
     "title": "Disk files (inodes) usage",
     "type": "graph",
     "description": "inodes (or index nodes) are filesystem objects (e.g. files and directories).\n\nOn many types of file system implementations, the maximum number of inodes is fixed at filesystem creation, limiting the maximum number of files the filesystem can hold. It is possible for a device to run out of inodes.\n\nWhen this happens, new files cannot be created on the device, even though there may be free space available.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3526 },
     "targets": [
      {
       "expr": "netdata_disk_inodes_inodes_average{instance=~\"$instance\"}",
       "legendFormat": "{{family}} {{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IPv4 networking:",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "IPv4 sockets used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3527 },
     "yaxes": [
      { "format": "short", "label": "sockets" }
     ],
     "targets": [
      {
       "expr": "netdata_ipv4_sockstat_sockets_sockets_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv4 packets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3534 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "netdata_ipv4_packets_packets_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv4 errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3541 },
     "yaxes": [
      { "format": "short", "label": "packets" }
     ],
     "targets": [
      {
       "expr": "netdata_ipv4_errors_packets_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv4 input errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3541 },
     "yaxes": [
      { "format": "short", "label": "packets" }
     ],
     "targets": [
      {
       "expr": "netdata_ipv4_errors_packets_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IPv4 networking: TCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "IPv4 TCP sockets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3622 },
     "yaxes": [
      { "format": "short", "label": "sockets" }
     ],
     "targets": [
      {
       "expr": "netdata_ipv4_sockstat_tcp_sockets_sockets_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv4 TCP connections",
     "type": "graph",
     "description": "The number of established TCP connections (known as `CurrEstab`). This is a snapshot of the established connections at the time of measurement (i.e. a connection established and a connection disconnected within the same iteration will not affect this metric).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3629 },
     "yaxes": [
      { "format": "short", "label": "active connections" }
     ],
     "targets": [
      {
       "expr": "netdata_ipv4_tcpsock_active_connections_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv4 TCP opens",
     "type": "graph",
     "description": "**active** or `ActiveOpens` is the number of outgoing TCP **connections attempted** by this host. **passive** or `PassiveOpens` is the number of incoming TCP **connections accepted** by this host.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3629 },
     "yaxes": [
      { "format": "short", "label": "connections" }
     ],
     "targets": [
      {
       "expr": "netdata_ipv4_tcpopens_connections_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv4 TCP packets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3637 },
     "yaxes": [
      { "format": "short", "label": "packets" }
     ],
     "targets": [
      {
       "expr": "netdata_ipv4_tcppackets_packets_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv4 TCP errors",
     "type": "graph",
     "description": "`InErrs` is the number of TCP segments received in error (including header too small, checksum errors, sequence errors, bad packets - for both IPv4 and IPv6). `InCsumErrors` is the number of TCP segments received with checksum errors (for both IPv4 and IPv6). `RetransSegs` is the number of TCP segments retransmitted.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3637 },
     "yaxes": [
      { "format": "short", "label": "packets" }
     ],
     "targets": [
      {
       "expr": "netdata_ipv4_tcperrors_packets_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "TCP connection aborts",
     "type": "graph",
     "description": "TCP connection aborts.\n\n**baddata** (`TCPAbortOnData`) happens while the connection is on `FIN_WAIT1` and the kernel receives a packet with a sequence number beyond the last one for this connection - the kernel responds with `RST` (closes the connection).\n\n**userclosed** (`TCPAbortOnClose`) happens when the kernel receives data on an already closed connection and responds with `RST`.\n\n**nomemory** (`TCPAbortOnMemory` happens when there are too many orphaned sockets (not attached to an fd) and the kernel has to drop a connection - sometimes it will send an `RST`, sometimes it won't.\n\n**timeout** (`TCPAbortOnTimeout`) happens when a connection times out.\n\n**linger** (`TCPAbortOnLinger`) happens when the kernel killed a socket that was already closed by the application and lingered around for long enough.\n\n**failed** (`TCPAbortFailed`) happens when the kernel attempted to send an `RST` but failed because there was no memory available.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3645 },
     "targets": [
      {
       "expr": "netdata_ip_tcpconnaborts_connections_persec_average{dimension=\"failed\",instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      },
      {
       "expr": "netdata_ip_tcpconnaborts_connections_persec_average{dimension!=\"failed\",instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv4 TCP handshake issues",
     "type": "graph",
     "description": "`EstabResets` is the number of established connections resets (i.e. connections that made a direct transition from `ESTABLISHED` or `CLOSE_WAIT` to `CLOSED`).\n\n`OutRsts` is the number of TCP segments sent, with the `RST` flag set (for both IPv4 and IPv6).\n\n`AttemptFails` is the number of times TCP connections made a direct transition from either `SYN_SENT` or `SYN_RECV` to `CLOSED`, plus the number of times TCP connections made a direct transition from the `SYN_RECV` to `LISTEN`.\n\n`TCPSynRetrans` shows retries for new outbound TCP connections, which can indicate general connectivity issues or backlog on the remote host.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 3652 },
     "targets": [
      {
       "expr": "netdata_ipv4_tcphandshake_events_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "TCP reordered packets by detection method",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 3652 },
     "targets": [
      {
       "expr": "netdata_ip_tcpreorders_packets_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "TCP out-of-order queue",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3663 },
     "targets": [
      {
       "expr": "netdata_ip_tcpofo_packets_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv4 TCP sockets memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3663 },
     "targets": [
      {
       "expr": "netdata_ipv4_sockstat_tcp_mem_KiB_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IPv4 networking: UDP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "IPv4 UDP sockets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2813 },
     "yaxes": [
      { "format": "short", "label": "sockets" }
     ],
     "targets": [
      {
       "expr": "netdata_ipv4_sockstat_udp_sockets_sockets_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv4 UDP packets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2813 },
     "yaxes": [
      { "format": "short", "label": "packets" }
     ],
     "targets": [
      {
       "expr": "netdata_ipv4_udppackets_packets_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv4 UDP sockets memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2820 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "expr": "netdata_ipv4_sockstat_udp_mem_KiB_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv4 UDP errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2820 },
     "yaxes": [
      { "format": "short", "label": "events" }
     ],
     "targets": [
      {
       "expr": "netdata_ipv4_udperrors_events_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IPv4 networking: ICMP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "IPv4 ICMP packets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2839 },
     "yaxes": [
      { "format": "short", "label": "packets" }
     ],
     "targets": [
      {
       "expr": "netdata_ipv4_icmp_packets_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv4 ICMP errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2839 },
     "yaxes": [
      { "format": "short", "label": "packets" }
     ],
     "targets": [
      {
       "expr": "netdata_ipv4_icmp_errors_packets_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv4 ICMP messages",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2847 },
     "yaxes": [
      { "format": "short", "label": "packets" }
     ],
     "targets": [
      {
       "expr": "netdata_ipv4_icmpmsg_packets_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IPv4 networking: UDP - Lite-No stats collected",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "IPv4 UDP-Lite packets",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 2866 },
     "yaxes": [
      { "format": "short", "label": "packets" }
     ],
     "targets": [
      {
       "expr": "netdata_ipv4_udplite_packets_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv4 UDP-Lite errors",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 2866 },
     "yaxes": [
      { "format": "short", "label": "packets" }
     ],
     "targets": [
      {
       "expr": "netdata_ipv4_udplite_errors_packets_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IPv4 networking: raw - No data collected",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "IPv4 raw sockets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2878 },
     "yaxes": [
      { "format": "short", "label": "sockets" }
     ],
     "targets": [
      {
       "expr": "netdata_ipv4_sockstat_raw_sockets_sockets_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IPv4 networking: fragments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "IPv4 fragments sent",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3700 },
     "targets": [
      {
       "expr": "netdata_ipv4_fragsout_packets_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv4 fragments reassembly - No data collected",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3700 },
     "targets": [
      {
       "expr": "netdata_ipv4_fragsin_packets_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IPv4 networking: broadcast",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "IPv4 broadcast bandwidth",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3701 },
     "targets": [
      {
       "expr": "netdata_ip_bcast_kilobits_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv4 broadcast packets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3701 },
     "targets": [
      {
       "expr": "netdata_ip_bcastpkts_packets_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IPv4 networking: multicast",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "IPv4 multicast packets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3702 },
     "targets": [
      {
       "expr": "netdata_ip_mcastpkts_packets_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv4 multicast bandwidth",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3702 },
     "targets": [
      {
       "expr": "netdata_ip_mcast_kilobits_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IPv4 networking: ECN",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "IPv4 ECN statistics",
     "type": "graph",
     "description": "[Explicit Congestion Notification (ECN)](https://en.wikipedia.org/wiki/Explicit_Congestion_Notification) is a TCP extension that allows end-to-end notification of network congestion without dropping packets.\n\nECN is an optional feature that may be used between two ECN-enabled endpoints when the underlying network infrastructure also supports it.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3703 },
     "targets": [
      {
       "expr": "netdata_ip_ecnpkts_packets_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IPv6 networking: packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "IPv6 packets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3704 },
     "targets": [
      {
       "expr": "netdata_ipv6_packets_packets_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv6 ECT packets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3704 },
     "targets": [
      {
       "expr": "netdata_ipv6_ect_packets_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IPv6 networking: tcp6",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "IPv6 TCP sockets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3705 },
     "targets": [
      {
       "expr": "netdata_ipv6_sockstat6_tcp_sockets_sockets_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IPv6 networking: udp6",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "IPv6 UDP sockets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3706 },
     "targets": [
      {
       "expr": "netdata_ipv6_sockstat6_udp_sockets_sockets_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv6 UDP packets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3706 },
     "targets": [
      {
       "expr": "netdata_ipv6_udppackets_packets_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv6 UDP errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3713 },
     "targets": [
      {
       "expr": "netdata_ipv6_udperrors_events_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IPv6 networking: raw6",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "IPv6 raw sockets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3707 },
     "targets": [
      {
       "expr": "netdata_ipv6_sockstat6_raw_sockets_sockets_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IPv6 networking: multicast6",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "IPv6 multicast bandwidth",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3708 },
     "targets": [
      {
       "expr": "netdata_ipv6_mcast_kilobits_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv6 multicast packets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3708 },
     "targets": [
      {
       "expr": "netdata_ipv6_mcastpkts_packets_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IPv6 networking: icmp6",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "IPv6 ICMP messages",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3709 },
     "targets": [
      {
       "expr": "netdata_ipv6_icmp_messages_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv6 ICMP errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3716 },
     "targets": [
      {
       "expr": "netdata_ipv6_icmperrors_errors_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv6 ICMP echo",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3723 },
     "targets": [
      {
       "expr": "netdata_ipv6_icmp_messages_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv6 router messages",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3723 },
     "targets": [
      {
       "expr": "netdata_ipv6_icmprouter_messages_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv6 neighbor messages",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3732 },
     "targets": [
      {
       "expr": "netdata_ipv6_icmpneighbor_messages_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv6 ICMP MLDv2 reports",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3732 },
     "targets": [
      {
       "expr": "netdata_ipv6_icmpmldv2_reports_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "IPv6 ICMP types",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3741 },
     "targets": [
      {
       "expr": "netdata_ipv6_icmptypes_messages_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network interfaces:",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "repeat": "net",
   "collapsed": true,
   "panels": [
    {
     "title": "Bandwidth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "Kbits" }
     ],
     "targets": [
      {
       "expr": "netdata_net_net_kilobits_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{family}} {{dimension}}"
      }
     ]
    },
    {
     "title": "Packets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
     "yaxes": [
      { "format": "short", "label": "packets" }
     ],
     "targets": [
      {
       "expr": "netdata_net_packets_packets_persec_average{instance=~\"$instance\"}",
       "legendFormat": "{{family}} {{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "[[view]]: cpu",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "repeat": "view",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU apps time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3711 },
     "targets": [
      {
       "expr": "netdata_apps_cpu_percentage_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "CPU user time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3718 },
     "targets": [
      {
       "expr": "netdata_apps_cpu_user_percentage_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "[[view]]: disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "repeat": "view",
   "collapsed": true,
   "panels": [
    {
     "title": "Disk reads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2906 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "expr": "netdata_apps_preads_KiB_persec_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Disk writes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2913 },
     "yaxes": [
      { "format": "KBs" }
     ],
     "targets": [
      {
       "expr": "netdata_apps_pwrites_KiB_persec_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Disk logical reads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2920 },
     "targets": [
      {
       "expr": "netdata_apps_lreads_KiB_persec_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Disk logical writes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2927 },
     "targets": [
      {
       "expr": "netdata_apps_lwrites_KiB_persec_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Open files",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2934 },
     "targets": [
      {
       "expr": "netdata_apps_files_open_files_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "CPU system time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2941 },
     "targets": [
      {
       "expr": "netdata_apps_cpu_system_percentage_average{instance=~\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "[[view]]: mem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "repeat": "view",
   "collapsed": true,
   "panels": [
    {
     "title": "Real memory (w/o shared)",
     "type": "graph",
     "description": "Real memory (RAM) used by applications. This does not include shared memory.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3769 },
     "targets": [
      {
       "expr": "netdata_apps_mem_MiB_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Minor page faults",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3776 },
     "targets": [
      {
       "expr": "netdata_apps_minor_faults_page_faults_persec_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Virtual memory",
     "type": "graph",
     "description": "Virtual memory allocated by applications. Please check [this article](https://github.com/firehol/netdata/wiki/netdata-virtual-memory-size) for more information.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3783 },
     "targets": [
      {
       "expr": "netdata_apps_vmem_MiB_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  {
   "title": "[[view]]: processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "repeat": "view",
   "collapsed": true,
   "panels": [
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short", "label": "threads" }
     ],
     "targets": [
      {
       "expr": "netdata_apps_threads_threads_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Processes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short", "label": "processes" }
     ],
     "targets": [
      {
       "expr": "netdata_apps_processes_processes_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  },
  { "title": "[[view]]: swap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 }, "repeat": "view" },
  {
   "title": "Swap memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "netdata_apps_swap_MiB_average{instance=\"$instance\"}",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Major page faults (swap read)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "none", "label": "page faults" }
   ],
   "targets": [
    {
     "expr": "netdata_apps_major_faults_page_faults_persec_average{instance=\"$instance\"}",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Pipes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short", "label": "open pipes" }
   ],
   "targets": [
    {
     "expr": "netdata_apps_pipes_open_pipes_average{instance=\"$instance\"}",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  { "title": "[[view]]: net", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 }, "repeat": "view" },
  {
   "title": "Open sockets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short", "label": "open sockets" }
   ],
   "targets": [
    {
     "expr": "netdata_apps_sockets_open_sockets_average{instance=\"$instance\"}",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Sensors: temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3836 },
     "repeat": "temp_sensor",
     "targets": [
      {
       "expr": "netdata_sensors_temperature_Celsius_average{instance=\"$instance\"}",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  }
 ]
}