---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name truenas-scale
spec:
  scheme: HTTPS
  tlsConfig:
    insecureSkipVerify: true
  staticConfigs:
    - targets:
        - "nas.${SECRET_DOMAIN}"
  metricsPath: /netdata/api/v1/allmetrics
  params:
    # format: prometheus | prometheus_all_hosts
    # You can use `prometheus_all_hosts` if you want Prometheus to set the `instance` to your hostname instead of IP 
    format: [ prometheus ]
    prefix: [ truenas]
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
