---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cyberchef
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        name: bjw-s
        kind: HelmRepository
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false  

  values:
    automountServiceAccountToken: false

    controllers:
      cyberchef:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: docker.io/mpepping/cyberchef
              tag: v10.19.4@sha256:91e04eaaa1ba1eac6b8e410d6f7b340e1ea0450d48ccbb52ec67ce6faa3672c5
            env:
              TZ: "${CONFIG_TZ}"
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 256Mi
    service:
      main:
        controller: cyberchef
        ports:
          http:
            port: &port 8000
    ingress:
      main:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          # nginx.ingress.kubernetes.io/auth-signin: |-
          #   https://${HOSTNAME}/outpost.goauthentik.io/start?rd=$escaped_request_uri
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Dev-Tools
          gethomepage.dev/name: CyberChef
        hosts:
          - host: &host "${HOSTNAME}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: *port
  
    # podSecurityContext:
    #   runAsUser: &uid ${APP_UID_CYBERCHEF:=1000}
    #   runAsGroup: *uid
    #   fsGroup: *uid
    #   fsGroupChangePolicy: Always
    # resources:
    #   requests:
    #     cpu: 10m
    #     memory: 128Mi
    #   limits:
    #     memory: 256Mi
