---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./scrapeconfig.yaml
configMapGenerator:
  - name: proxmox-node-exporter
    files:
      - proxmox-node-exporter.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    grafana_folder: Proxmox
  labels:
    grafana_dashboard: "true"
