---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: connect
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.17.0
  url: oci://ghcr.io/home-operations/charts-mirror/connect
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token.actions.githubusercontent.com$"
        subject: "^https://github.com/home-operations/charts-mirror.*$"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword-connect
  namespace: security
spec:
  chartRef:
    kind: OCIRepository
    name: connect
  interval: 30m
  install:
    crds: CreateReplace
  maxHistory: 3
  upgrade:
    crds: CreateReplace
  uninstall:
    keepHistory: false
  driftDetection:
    mode: enabled
  valuesFrom:
    - kind: ConfigMap
      name: external-secrets-values

  values:
    ingress:
      enabled: false
