connect:
  api:
    resources:
      limits: {}
    serviceMonitor:
      enabled: true
  pdb:
    enabled: true
    minAvailable: 1
  replicas: 2
  serviceType: ClusterIP
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule