---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: redis-secret
    template:
      engineVersion: v2
      data:
        REDIS_PASSWORD: "{{ .redis_password }}"
  dataFrom:
    - extract:
        key: redis
