---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: Redis
        group: Database
        url: tcp://redis.database.svc.cluster.local:6379
        interval: 1m
        ui:
          hide-url: true
          hide-hostname: true
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: telegram
            send-on-resolved: true
