---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name stirling-pdf-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SECURITY_OAUTH2_ISSUER:  "https://auth.${SECRET_DOMAIN}/application/o/stirling-pdf/.well-known/openid-configuration"
        SECURITY_OAUTH2_CLIENTID: "{{ .stirling_oidc_client_id }}"
        SECURITY_OAUTH2_CLIENTSECRET: "{{ .stirling_oidc_client_secret }}"
        SECURITY_OAUTH2_PROVIDER: "authentik"
        SECURITY_OAUTH2_USEASUSERNAME: "email"
        SECURITY_OAUTH2_SCOPES: "openid, profile, email"

        # Provider
        SECURITY_OAUTH2_CLIENT_AUTHENTIK_ISSUER: "https://auth.${SECRET_DOMAIN}/application/o/stirling-pdf/.well-known/openid-configuration"
        SECURITY_OAUTH2_CLIENT_AUTHENTIK_CLIENTID: "{{ .stirling_oidc_client_id }}"
        SECURITY_OAUTH2_CLIENT_AUTHENTIK_CLIENTSECRET: "{{ .stirling_oidc_client_secret }}"
        SECURITY_OAUTH2_CLIENT_AUTHENTIK_SCOPES: "openid, profile, email"
        SECURITY_OAUTH2_CLIENT_AUTHENTIK_USEASUSERNAME: email
        
  dataFrom:
    - extract:
        key: stirling-pdf