# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app stirling-pdf
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      app:
        annotations:
          reloader.stakater.com/auto: "true"
          secret.reloader.stakater.com/reload: &secret stirling-pdf-secret
        containers:
          app:
            image:
              repository: ghcr.io/stirling-tools/s-pdf
              tag: 0.46.2-fat@sha256:df615ff58f1827cc814cb118a6d834b81a8b24a2edb6a04a653fb0c01f070bcf
              pullPolicy: IfNotPresent
            env:
              TZ: ${CONFIG_TIMEZONE}
              DOCKER_ENABLE_SECURITY: "true"
              SECURITY_ENABLELOGIN: "true"
              # SECURITY_LOGINMETHOD: "oauth2"
              # SECURITY_OAUTH2_ENABLED: "true"
              # SECURITY_OAUTH2_AUTOCREATEUSER: "true"
              INSTALL_BOOK_AND_ADVANCED_HTML_OPS: "true"
            envFrom:
              - secretRef:
                  name: *secret
            probes:
              liveness: &probe
                enabled: true
                type: HTTP
                path: /api/v1/info/status
              readiness: *probe
              startup:
                <<: *probe
                spec:
                  failureThreshold: 90
                  periodSeconds: 5
            securityContext:
              readOnlyRootFilesystem: true
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch

    persistence:
      config:
        enabled: true
        existingClaim: stirling-pdf
        globalMounts:
          - path: /configs
      logs:
        enabled: true
        type: emptyDir
      tmp:
        enabled: true
        type: emptyDir
      tessdata:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /usr/share/tessdata

    service:
      app:
        controller: app
        ports:
          http:
            port: 8080

    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Stirling PDF
          gethomepage.dev/description: PDF Viewer and Editor
          gethomepage.dev/group: Services
          gethomepage.dev/icon: stirling-pdf.svg
        hosts:
          - host: ${HOSTNAME}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
