---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ai-ollama
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  targetNamespace: ai
  path: "./kubernetes/apps/ai/ollama/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn:
    - name: external-secrets-stores
