apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:ufiE/bzA51cFgA0BgexdUaIjh4wJBRSsANmkfVJjVN3I2HeZ,iv:c6eGu/IgI6fVfyNXGyWjBSHTaP2Fa1Mtu9ssmHzSphk=,tag:tfgtDOhcHd2eQYRwBrT5Og==,type:str]
    credentials.json: ENC[AES256_GCM,data:R8hKhSRzIZIPwuRw8r09z7JrEMTQPBmWJLbUbi+vCiozNJzyYECv8KGOitE8tfiuXszdciVQPmXvloE8teadD0xBmhM1N7j7WzdAJsFE/lCHON1XM7ua5qak95YEAt64JdboHnjH8isHLQWpTw+lNwXx0c3q95YxSk/Za5P3YvpBQajoecT6mvtbH5neDz1aHmqmqjlzBWhUnZSKQzyC3A+mFa7xAdij8Au8tOAXXg==,iv:qwXUhJ0fMl5Cu4r4XrXUwSx5/ChQQkXUmGQLpcp7cXY=,tag:aOP8l5dcZDWIdrHgXaQJWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12jenp34w79lv5f4m428dk6h9jxtma4r3teujmg5wmh7p295ryfvqhjykad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONzFrdGNycUJON3FwL1lq
            MVZaL083aUs4eDZqTHNOaUxKMUlna0ZKNlRJClZSMSt2VHcvaDB5V295STRCUUla
            bVNXVmRlWFBSMU9YVTdUWFNNWE1NenMKLS0tIHVvT1M2MC9ya3NWMUU1YWdzWEhU
            R2NmRFFhczN2cXA1SnpYdTIrUmU4R1kKug/WmH7yR1bUbw3YvFCyyNW6Qwo70l06
            /7WcHc6jpw7EAKF7IYCMBcWiFvyeYqUscxoFdqOk+UEsji2g2AmJMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-08T06:43:58Z"
    mac: ENC[AES256_GCM,data:atqsQknRgQr+3x2CuNlrCxPqClsy3Wj3ACjYWYxL/QKX32CVR6oJzMCca3OgNX7vb6f3dgSuyAdWyjLVBj+LaU0TWz0CWPU8uj0O+ySmF6sA3kqxvq0ZvHwJrreR706f/0ST8mL93XZ/qPPJxOGDtaLCYOCKQ7UH9VbXIC8nfd8=,iv:HFy/IP6EHbQEz2Zjoeg0V7EG7t/VVtnSbQXu4fX7IGw=,tag:tjeSq7XwN7fA9VpEJ0tkMw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
