---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: gha-runner-scale-set
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.11.0
  url: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name arc-sklab-dev
  # annotations:
  #   reloader.stakater.com/auto: "true"
  #   # Add this to make Flux recreate when the secret changes
  #   reconcile.fluxcd.io/requestedAt: "$(date +%s)"
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: actions-runner-controller
      namespace: actions-runner-system
    - name: rook-ceph-external
      namespace: rook-ceph
  valuesFrom:
    - targetPath: githubConfigSecret.github_app_id
      kind: Secret
      name: actions-runner-controller-secret
      valuesKey: ACTION_RUNNER_CONTROLLER_GITHUB_APP_ID
    - targetPath: githubConfigSecret.github_app_installation_id
      kind: Secret
      name: actions-runner-controller-secret
      valuesKey: ACTION_RUNNER_CONTROLLER_GITHUB_INSTALLATION_ID
    - targetPath: githubConfigSecret.github_app_private_key
      kind: Secret
      name: actions-runner-controller-secret
      valuesKey: ACTION_RUNNER_CONTROLLER_GITHUB_PRIVATE_KEY
  values:
    githubConfigUrl: https://github.com/sklab-dev

    minRunners: 1
    maxRunners: 3

    containerMode:
      type: "dind"

    controllerServiceAccount:
      name: actions-runner-controller
      namespace: actions-runner-system
  ######################################################################################################
    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/onedr0p/actions-runner:2.322.0@sha256:9db27092b7caab08b1dc08d5e639a3340f6e0d6ae2f91aaf93e740bd28ad9306
            command: ["/home/runner/run.sh"]
  ######################################################################################################
    serviceAccountName: actions-runner

