---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app authentik
  namespace: flux-system
spec:
  path: ./kubernetes/apps/security/authentik/app
  targetNamespace: security
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  prune: true
  wait: false
  interval: 10m
  dependsOn:
    - name: cloudnative-pg-cluster
    - name: external-secrets-stores
    - name: redis
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: auth
