---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ns.yaml
  - ./cloudnative-pg/ks.yaml
  - ./emqx/ks.yaml
  - ./redis/ks.yaml
  - ./ferretdb/ks.yaml
