---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name authentik-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        # Authentik DBs
        AUTHENTIK_POSTGRESQL__HOST: &dbhost postgres17-rw.database.svc.cluster.local
        AUTHENTIK_POSTGRESQL__NAME: &dbname "{{ .postgres_dbname }}"
        AUTHENTIK_POSTGRESQL__USER: &dbuser "{{ .postgres_user }}"
        AUTHENTIK_POSTGRESQL__PASSWORD: &dbpass "{{ .postgres_password }}"
        AUTHENTIK_REDIS__DB: "1"
        AUTHENTIK_SECRET_KEY: "{{ .authentik_secret_key }}"

        # Authentik SMTP
        AUTHENTIK_EMAIL__HOST: "{{ .smtp_host }}"
        AUTHENTIK_EMAIL__PORT: "{{ .smtp_port }}"
        AUTHENTIK_EMAIL__USERNAME: "{{ .smtp_username }}"
        AUTHENTIK_EMAIL__PASSWORD: "{{ .smtp_password }}"
        AUTHENTIK_EMAIL__USE_SSL: "true"
        AUTHENTIK_EMAIL__FROM: "Authentik <auth@${SECRET_DOMAIN}>"

        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .postgres_super_password }}"

        AUTHENTIK_SESSION_STORAGE : db
        AUTHENTIK_REDIS__HOST: dragonfly-operator.database.svc.cluster.local
        # Authentik S3
        # AUTHENTIK_STORAGE__MEDIA__S3__ENDPOINT: '{{ .AUTHENTIK_STORAGE__MEDIA__S3__ENDPOINT }}'
        # AUTHENTIK_STORAGE__MEDIA__S3__BUCKET_NAME: '{{ .AUTHENTIK_STORAGE__MEDIA__S3__BUCKET_NAME }}'
        # AUTHENTIK_STORAGE__MEDIA__S3__CUSTOM_DOMAIN: '{{ .AUTHENTIK_STORAGE__MEDIA__S3__CUSTOM_DOMAIN }}'
        # AUTHENTIK_STORAGE__MEDIA__S3__ACCESS_KEY: '{{ .AUTHENTIK_STORAGE__MEDIA__S3__ACCESS_KEY }}'
        # AUTHENTIK_STORAGE__MEDIA__S3__SECRET_KEY: '{{ .AUTHENTIK_STORAGE__MEDIA__S3__SECRET_KEY }}'
  dataFrom:
    - extract:
        key: authentik
    - extract:
        key: cloudnative-pg
    - extract:
        key: smtp