---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  chart:
    spec:
      chart: authentik
      version: 2024.12.1
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  interval: 30m
  values:
    global:
      deploymentAnnotations:
        secret.reloader.stakater.com/reload: &secret authentik-secret
      env: &env
        AUTHENTIK_SESSION_STORAGE : db
        AUTHENTIK_REDIS__HOST: dragonfly.database.svc.cluster.local
      envFrom:
        - secretRef:
            name: *secret
    server:
      replicas: 1
      initContainers:
        - name: init-db
          image: ghcr.io/onedr0p/postgres-init:16.6
          envFrom:
            - secretRef:
                name: *secret
      resources:
        requests:
          cpu: 50m
          memory: 500Mi
        limits:
          memory: 800Mi
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      ingress:
        app:
          enabled: true
          ingressClassName: public
          annotations:
            external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          hosts:
            - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
              paths:
                - path: /
                  service:
                    identifier: app
                    port: http

    worker:
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 500Mi
        limits:
          memory: 1200Mi
    authentik:
      log_level: debug
      redis:
        host: dragonfly.database.svc.cluster.local
      error_reporting:
        enabled: false
    redis:
      enabled: false 
      storageClassName: ceph-block

    prometheus:
      rules:
        enabled: true
