---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  chart:
    spec:
      chart: authentik
      version: 2025.6.4
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  interval: 30m
  values:
    global:
      deploymentAnnotations:
        secret.reloader.stakater.com/reload: &secret authentik-secret
      # env:
      #   AUTHENTIK_STORAGE__MEDIA__BACKEND: file
      envFrom:
        - secretRef:
            name: *secret

    authentik:
      log_level: info   
      error_reporting:
        enabled: false

    postgres:
      enabled: false

    prometheus:
      rules:
        enabled: true

    redis:
      enabled: false

    server:
      podAnnotations:
        secret.reloader.stakater.com/reload:
      initContainers:
        - name: init-db
          image: ghcr.io/onedr0p/postgres-init:16.8
          envFrom:
            - secretRef:
                name: *secret
      ingress:
        enabled: true
        ingressClassName: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          # https://kubernetes.github.io/ingress-nginx/user-guide/miscellaneous/#websockets
          nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Security
          gethomepage.dev/name: Authentik
        hosts:
          - "auth.${SECRET_DOMAIN}"
            # paths:
            #   - path: /
            #     service:
            #       identifier: app
            #       port: http
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
    
    # Need to sort out the storage
    # persistence:
    #   config:
    #     enabled: true
    #     existingClaim: *app
    #     globalMounts:
    #       - path: /data/config

