---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: mongo
        group: data
        url: tcp://mongodb.database.svc.cluster.local:27017
        interval: 1m
        ui:
          hide-url: true
          hide-hostname: true
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: pushover
