---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mongodb
  namespace: database
spec:
  interval: 15m
  chart:
    spec:
      chart: mongodb
      version: 16.5.33
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    annotations:
      reloader.stakater.com/auto: "true"
    persistence:
      existingClaim: *app
      
    auth:
      enabled: true
      rootUser: "root"
      existingSecret: &secret mongodb-secret
    passwordUpdateJob:
      enabled: true
      rootUser: "root"
      existingSecret: *secret
    metrics:
      enabled: true
