---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cert-manager-secret
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: cert-manager-secret
    template:
      engineVersion: v2
      data:
        api-token: "{{ .CLOUDFLARE_API_KEY }}"
  data:
    - secretKey: CLOUDFLARE_API_KEY
      remoteRef:
        key: CLOUDFLARE_API_KEY