apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:YoED/moUK/BeTL1AqM2+8ozb0UZkLdCNOTtC5trHc0URBXIEjMBHQQ==,iv:UIbePPGNxojbRrquOXlQEq+NN2xvjfBmh6ZPuAx/yXI=,tag:TFoAhX+o4d3OjDXoFI2keA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12jenp34w79lv5f4m428dk6h9jxtma4r3teujmg5wmh7p295ryfvqhjykad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVC94TDh6QXZOYVVtbVVy
            OWt0elpvbGVSUVlGcGxkWm9uMWNuNlQvV3dRClV6VDl6MDFIOHpvaG1TVlkvOFVZ
            Uk1JSTFwNE5Vend3TUNnbnViOHFxVkkKLS0tIG9XVHpuWmJ3SWxlWWpXTit6MWhy
            bzh4R0JmMXNJSlBGS0VXS2FGek42UkUKZMV+S/m1aCwEJi/HqRqkrxp9BX5WUgwe
            XgTX4LwOS8rccFfs7KBO0aLncdMCC+y3o3t58h0QOxwpLtqEde3Cyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-08T06:43:58Z"
    mac: ENC[AES256_GCM,data:6IBkPapPQyD009KHCVXHqSMbppB0Sb9unPKwcZml9BAddW+IYJvo0VS2xx2AYaPfQleAdlb260UM+ILKesrR4jVqApEZsY9MNamePRR5SovbtjEl7/1bBJCHbfROx+aCkgMmybwsY4CJlSK+FcktBwZpYnwrg3qo5U9hjNKsowM=,iv:9m/xNg4aB05ORd38BRcPX3xVLZDPvU88qLrkf9MS6Og=,tag:exeLh4oFEr8xHgZwCZt+tA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
