apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:cE1oTQMN/kF4gF+KKObDjl4bPbLJUU4UamLv/XpBVBlaqymObtPZ+g==,iv:bB0lxFrXHrXx+8kZCbt5rGeRSyWQSQNH1h6OBpQ6V4o=,tag:ebK3yCFVrqCTsroppJtozw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12jenp34w79lv5f4m428dk6h9jxtma4r3teujmg5wmh7p295ryfvqhjykad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWekRUZjhzVkF3RWxlMTV3
            aGdocHhYYmVweTFJUXdTU2hVT1BteE43VEhVCnVhMXNFQWNwWXFNdXhVSWYxM0kr
            N2xaZER0V2ZkSHRkd3k2QjhwT1ZqSzAKLS0tIG40ckRvYlUrTlFLdXhFclRXSDJL
            NVVLbTJmOHkxbGwvRGxNVVNOVDNwMzAKY+AanZ3d89JMivbZLpmciXXMFuHKOgRX
            q2OVSa+UbFy6tH9yKsl0JWBy2XFS7tEkhX+mdW6MoBI/0Zm+cFrBkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-08T21:16:17Z"
    mac: ENC[AES256_GCM,data:QkFpmwzuFsQvdU5o1dBOmuDqMB/UBvVTNGa3zXEKuoz+SrXJCzvrE8//dKXefOxsWOli8Ewpht5D4jESIZlO0vIAIULgRjr744/xcz2SwSKYKf1xf2rLC2/Q5lCgvgwJ1BGHku/Zl3+ceYQc9Eh+WbArPzu0LjQFX6X0aP3hG2M=,iv:IWmcXC92LUPZmgnk2NLkcFGcu/BFPSYs/3ofzYQWNHI=,tag:Ff/pewtGhcmQiNPS8c/NYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
