apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:J+2Oq5b+7UB2QHzzd4j6U4H84Fd6x77nibjPB3k4N5gkZzSN1otI/A==,iv:nl1i9WGFtx5W8VOO0ZSzaGn4wnsa+NF97Zt8cTN2M04=,tag:1VPocl7qvxQkKL9EMAFAcw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12jenp34w79lv5f4m428dk6h9jxtma4r3teujmg5wmh7p295ryfvqhjykad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RkFzQmxPNTRsUlA5Wk5z
            Qm1tM0JPZ243d2RZOWoydGErenRtNUdEcXpRCitsaFhaQW1MbU5wOU5TblBTYTBh
            NU1vd2huZ1NxTEpLYVBCTTBuNFlwQTgKLS0tIFo2d01ZKzNyN2I3NDR5eVBvdGZy
            MkZxZkZQWklRNDFhcGZQTE1TOVlMTFkKkkLuWmT2x/TAYMrsisZbMNG16i1fl3zQ
            tg+XYkCcU16x8hvBi4HEt5ZeWQCBP5MeCWMFBw1uJ8IRn/OegV1Pgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-08T04:57:26Z"
    mac: ENC[AES256_GCM,data:regzyHnBDWEH/7EB9uXXO/TG4YU+GNK2u6FmA+17MF/lSIbwrnDulfso82ywJnQl0AmrpJh1+j0uS4L5QRohfV6VVMVDL9DpParcpkIlpewz0EEGY2dOh0Qt3lJQxeH/+nf/P5wSwZgRbn+r1nVofARX2ywN/nOVW/6oVhCqPHI=,iv:+WKxBrRYzh2ADOZTKqGq2RpggSssUOFnEagC0fERvdM=,tag:j+LYf4OVzm3Gon2+UiE4iA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
