---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname matter-server
  namespace: flux-system
spec:
  targetNamespace: home-automation
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./kubernetes/apps/home-automation/matter-server/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false # no flux ks dependents
  postBuild:
    substitute:
      APP: *appname
      APP_UID: "0"
      APP_GID: "0"
      VOLSYNC_CLAIM: matter-server
      VOLSYNC_CAPACITY: 1Gi
  dependsOn:
    # - name: topolvm
    - name: volsync
