---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-volsync
provisioner: nfs.csi.k8s.io
parameters:
  server: nas.${SECRET_DOMAIN}
  share: /mnt/storage/
  # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
  # csi.storage.k8s.io/provisioner-secret-name: "mount-options"
  # csi.storage.k8s.io/provisioner-secret-namespace: "default"
reclaimPolicy: retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
