---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gatus
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: gatus-secret
    template:
      engineVersion: v2
      data:
        PUSHOVER_TOKEN: "{{ .gatus_pushover_token }}"
        PUSHOVER_USER_KEY: "{{ .user_key }}"
        INIT_POSTGRES_DBNAME: "{{ .pg_dbname }}"
        INIT_POSTGRES_HOST: postgres17-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .pg_user }}"
        INIT_POSTGRES_PASS: "{{ .pg_password }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .password }}"

  dataFrom:
  - extract:
      key: gatus
  - extract:
      key: cloudnative-pg
  - extract:
      key: pushover
  