---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: it-tools
  namespace: flux-system
spec:
  path: ./kubernetes/apps/dev-tools/it-tools/app
  targetNamespace: dev-tools
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  commonMetadata:
    labels:
      app.kubernetes.io/name: it-tools
  prune: true
  wait: false
  interval: 10m
  postBuild:
    substitute:
      HOSTNAME: it-tools.${SECRET_DOMAIN}
