# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app klipper-exporter
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      klipper:
        containers:
          app:
            image:
              repository: ghcr.io/scross01/prometheus-klipper-exporter
              tag: v0.12.0@sha256:d6dcd19f87021a7734633e8ceb94b45ce03e1b5251fd996092c0e35a92fcbc38
            env:
              TZ: America/New_York
            probes:
              liveness:
                enabled: true
                spec:
                  tcpSocket:
                    port: &port 9101
              readiness:
                enabled: true
                spec:
                  tcpSocket:
                    port: *port
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: klipper
        ports:
          http:
            port: *port
    serviceMonitor:
      app:
        serviceName: klipper
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 2m # Unifi API only polls at 2m intervals
            scrapeTimeout: 10s

