# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app klipper-exporter
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      klipper:
        containers:
          app:
            image:
              repository: ghcr.io/scross01/prometheus-klipper-exporter
              tag: v0.13.0@sha256:4b55f39d1a4540d1e018f70224b2ad849d73963c181f936924bc18267df3ab82
            env:
              TZ: America/New_York
            args: [
              "--web.listen-address" , ":80",
            ]
            probes:
              liveness:
                enabled: true
                spec:
                  httpGet:
                    path: /metrics
                    port: &port 80
              readiness:
                enabled: true
                spec:
                  httpGet:
                    path: /metrics
                    port: *port
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
    service:
      app:
        controller: klipper
        ports:
          http:
            port: *port
    serviceMonitor:
      app:
        serviceName: klipper
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 2m # Unifi API only polls at 2m intervals
            scrapeTimeout: 10s

