---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name merge-wallet-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MERGE_WALLET_RPC_USER: "{{ .merge_wallet_rpc_user }}"
        MERGE_WALLET_RPC_PASSWORD: "{{ .merge_wallet_rpc_password }}"

  dataFrom:
  - extract:
      key: block-explorer-merge