---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cyberchef
  namespace: flux-system
spec:
  path: ./kubernetes/apps/dev-tools/cyberchef/app
  targetNamespace: dev-tools
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: cyberchef
  prune: true
  wait: false
  interval: 10m
  postBuild:
    substitute:
      HOSTNAME: cyberchef.${SECRET_DOMAIN}
