---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app paperless-ngx
  namespace: flux-system
spec:
  targetNamespace: observability
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/paperless/paperless-ngx/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  timeout: 15m

  dependsOn:
    - name: external-secrets-stores
    - name: csi-driver-nfs
    - name: redis
    - name: cloudnative-pg-cluster
    - name: volsync
    # - name: database-dragonfly-cluster
    # - name: security-secret-store
    # - name: storage-democratic-csi-nfs
    # - name: storage-volsync  
  postBuild:
    substitute:
      APP: *app
      HOSTNAME: paperless.${SECRET_DOMAIN}
      GATUS_SUBDOMAIN: docs
      GATUS_PATH: /status.php
      VOLSYNC_CAPACITY: 50Gi
      VOLSYNC_CACHE_CAPACITY: 5Gi
      VOLSYNC_TIME: 0 3 * * *