---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
data:
  PUBLIC_DOMAIN: sklab.dev
  PRIVATE_DOMAIN: sklab.dev
  CONFIG_TIMEZONE: America/New_York
  CONFIG_IPV4_NATIVE_ROUTING_CIDR: 10.11.0.0/16
  CONFIG_BGP_PUBLIC_POOL_CIDR: 10.11.0.0/16
  CONFIG_BGP_PRIVATE_POOL_CIDR: 10.12.0.0/16
  CONFIG_L2_POOL_PUBLIC_CIDR: 10.10.0.192/27
  CONFIG_L2_POOL_PRIVATE_CIDR: 10.10.0.224/27
  CONFIG_NAS_IPV4_ADDRESS: 10.10.0.40
