---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name n8n
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: *name
    template:
      data:
        # App
        N8N_ENCRYPTION_KEY: "{{ .secret_encryption_key }}"

        DB_TYPE: postgresdb
        DB_POSTGRESDB_DATABASE: &dbname "{{ .postgres_dbname }}"
        DB_POSTGRESDB_HOST: &dbhost postgres17-rw.database.svc.cluster.local
        DB_POSTGRESDB_USER: &dbuser "{{ .postgres_user }}"
        DB_POSTGRESDB_PASSWORD: &dbpass "{{ .postgres_password }}"
        DB_POSTGRESDB_PORT: "5432"

        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .postgres_super_password }}"

  dataFrom:
    - extract:
        key: /cloudnative-pg
    - extract:
        key: /n8n
