---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nginx-external
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: nginx-external-maxmind-secret
    template:
      engineVersion: v2
      data:
        MAXMIND_LICENSE_KEY: "{{ .license_key }}"
  dataFrom:
    - extract:
        key: maxmind
