---
# cephobjectstore.yaml
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: ceph-objectstore
spec:
  gateway:
    externalRgwEndpoints:
    - ip: ${SECRET_DOMAIN}   # Adjust this IP if you have a VIP / HAProxy later
    port: 7480
    securePort: 0
  preservePoolsOnDelete: true

---
# storageclass-bucket.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-bucket
provisioner: rook-ceph.ceph.rook.io/bucket
parameters:
  objectStoreName: ceph-objectstore
  objectStoreNamespace: rook-ceph
  region: us-east-1