---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unpoller
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: unpoller-secret
    template:
      engineVersion: v2
      data:
        UP_UNIFI_DEFAULT_USER: "{{ .unifi_unpoller_user }}"
        UP_UNIFI_DEFAULT_PASS: "{{ .unifi_unpoller_password }}"
        UP_UNIFI_DEFAULT_URL: "{{ .unifi_address }}"
  dataFrom:
  - extract:
      key: unifi
