---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unpoller
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: unpoller-secret
    template:
      engineVersion: v2
      data:
        UP_UNIFI_DEFAULT_USER: "{{ .UNIFY_UNPOLLER_USER }}"
        UP_UNIFI_DEFAULT_PASS: "{{ .UNIFY_UNPOLLER_PASSWORD }}"
  data:
    - secretKey: UNIFY_UNPOLLER_USER
      remoteRef:
        key: 	UNIFY_UNPOLLER_USER
    - secretKey: UNIFY_UNPOLLER_PASSWORD
      remoteRef:
        key: UNIFY_UNPOLLER_PASSWORD

