---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: grafana-admin-secret
    template:
      engineVersion: v2
      data:
        admin-user: "{{ .GRAFANA_ADMIN_USERNAME }}"
        admin-password: "{{ .GRAFANA_ADMIN_PASSWORD }}"
  data:
    - secretKey: GRAFANA_ADMIN_USERNAME
      remoteRef:
        key: GRAFANA_ADMIN_USERNAME
    - secretKey: GRAFANA_ADMIN_PASSWORD
      remoteRef:
        key: GRAFANA_ADMIN_PASSWORD
