apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:dMzH+j/t6H4J,iv:ka7OZ1YUaFyiKdLjyzls3a5CFvnlx+aG4wwtx5XlGjo=,tag:irZKapmoLxkSrFSLcfUm2w==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:7lhV/DlhUPbjf584xI07zWTxLMT/EzPjCl40,iv:8EUmeMBn++KQVkgpLImZsSDQHc+dNbbCWObG+HsAQWU=,tag:CIVQipw5cwpYyHhuYcFXSQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:3M9Cj9L8FaNRJnAZSH8joc4ylE2I6NgbxRWOVmizNbvHr3/R,iv:1jQplBewLBFXS/p5RJerPc0Hkp3a2iMsNdXgV/1vU0k=,tag:3/Sia6nC1g267VTg4oJFaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12jenp34w79lv5f4m428dk6h9jxtma4r3teujmg5wmh7p295ryfvqhjykad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TjhaMkJnT0o1UCtnaElK
            enQ0UFROMDBJbzlKbE9pekFDRHZIeXBLUFVFCnNVV3RyL24rVzZYUk1ENElWRGVF
            b1AzbUlybUNYVk9UempwMjEvcng2M2MKLS0tIG9uUXZITk9hd2NaYlVRUzBzWGd2
            L200aTUvR2lMVitabVhJcXFtNDlIVm8KgcKEF12346dk7ifk3x90gtn54yN794Qz
            OVrntuVcxm6XXFBLh4VFefRWW7wTnABcY8BOMKy0Wu1SE7dMtj+Vnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-08T19:46:03Z"
    mac: ENC[AES256_GCM,data:xxYoUJTtCcY3JPN0FdHTdJHzr6d1SUBbBUSek4wtjdN0L1YCHhCstZTCXu4bOeAEg/OZrj8qkeJ7S/vUdqIs2J2TfrlGHd73niNFvbfLQyrwpHDChb4ZZB17lmztW18k4aCE8YImfLwOvPN/Nhwl5012cmfaA4CXPwxKL09TAOk=,iv:fMVIN1/4rU8pbXpPHxSpAQb/mOwwnSeuZYYGDJz7ovU=,tag:M1cvZIQJobK/BaCHT6zhpQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
