---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-ai
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: paperless-ai-secret
    template:
      data:
        PAPERLESS_API_TOKEN: '{{ .paperless_admin_user_token }}'
        PAPERLESS_USERNAME: '{{ .paperless_admin_user_name }}'
        OPENAI_API_KEY: '{{ .openai_paperless_ai_api_token }}'
  dataFrom:
    - extract:
        key: paperless
    - extract:
        key: openai
