---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: cloudflared-secret
    template:
      engineVersion: v2
      data:
        TUNNEL_ID: "{{ .CLOUDFLARE_TUNNEL_ID }}"
        credentials.json: |
          {
            "AccountTag": "{{ .CLOUDFLARE_TUNNEL_ACCOUNT }}",
            "TunnelSecret": "{{ .CLOUDFLARE_TUNNEL_SECRET }}",
            "TunnelID": "{{ .CLOUDFLARE_TUNNEL_ID }}"
          }
  data:
    - secretKey: CLOUDFLARE_TUNNEL_ID
      remoteRef:
        key: CLOUDFLARE_TUNNEL_ID
    - secretKey: CLOUDFLARE_TUNNEL_ACCOUNT
      remoteRef:
        key: CLOUDFLARE_TUNNEL_ACCOUNT
    - secretKey: CLOUDFLARE_TUNNEL_SECRET
      remoteRef:
        key: CLOUDFLARE_TUNNEL_SECRET
