---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-unifi
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: external-dns-unifi-secret
    template:
      engineVersion: v2
      data:
        EXTERNAL_DNS_UNIFI_USER: "{{ .UNIFY_ADMIN_USER }}"
        EXTERNAL_DNS_UNIFI_PASS: "{{ .UNIFY_ADMIN_PASSWORD }}"
  data:
    - secretKey: UNIFY_ADMIN_USER
      remoteRef:
        key: UNIFY_ADMIN_USER
    - secretKey: UNIFY_ADMIN_PASSWORD
      remoteRef:
        key: UNIFY_ADMIN_PASSWORD