---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name paperless-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Paperless
        PAPERLESS_DBENGINE: postgresql
        PAPERLESS_DBPORT: "5432"
        PAPERLESS_DBHOST: &dbhost postgres-17-rw.database.svc.cluster.local
        PAPERLESS_DBNAME: &dbname "{{ .paperless_db_name}}"
        PAPERLESS_DBUSER: &dbuser "{{ .paperless_db_user }}"
        PAPERLESS_DBPASS: &dbpass "{{ .paperless_db_password }}"
        PAPERLESS_ADMIN_USER: "{{ .paperless_admin_user_name }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .paperless_admin_user_password }}"
        PAPERLESS_SECRET_KEY: "{{ .paperless_secret_key }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .postgres_super_password }}"
        # Redis
        PAPERLESS_REDIS: "redis://{{ .redis_password }}@redis.database.svc.cluster.local:6379/2"

        # OIDC
        PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
        PAPERLESS_ACCOUNT_ALLOW_SIGNUPS: "false"
        PAPERLESS_SOCIALACCOUNT_ALLOW_SIGNUPS: "true"
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: |
          {
            "openid_connect": {
                "APPS": [
                    {
                        "provider_id": "authentik",
                        "name": "Authentik",
                        "client_id": "{{ .paperless_oidc_client_id }}",
                        "secret": "{{ .paperless_oidc_client_secret }}",
                        "settings": {
                            "server_url": "https://auth.${SECRET_DOMAIN}/application/o/paperless/.well-known/openid-configuration"
                        }
                    }
                ]
            }
          }
  dataFrom:
    - extract:
        key: paperless
    - extract:
        key: cloudnative-pg
    - extract:
        key: redis
