apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-documents-paperless
spec:
  capacity:
    storage: 50Gi
  accessModes: 
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - hard
    - noatime
    - nodiratime
    - uid=3011 # para
    - gid=3014 # para
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: nfs-documents-paperless
    volumeAttributes:
      server: nas.${SECRET_DOMAIN}
      share: /mnt/storage/PARA/2-Areas/Documents
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-documents-paperless
spec:
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: nfs-documents-paperless