---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: &name ${VOLSYNC_CLAIM}
spec:
  accessModes: ["ReadWriteMany"]
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: *name
  resources:
    requests:
      storage: 50Gi
  storageClassName: ceph-block
  volumeMode: Filesystem
