---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secret pgadmin-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        PGADMIN_DEFAULT_EMAIL: "{{ .pgadmin_default_email }}"
        PGADMIN_DEFAULT_PASSWORD: "{{ .pgadmin_default_password }}"
        config_local.py: |-
          AUTHENTICATION_SOURCES = ['oauth2', 'internal']
          MASTER_PASSWORD_REQUIRED = False
          OAUTH2_AUTO_CREATE_USER = True
          OAUTH2_CONFIG = [{
              'OAUTH2_NAME': 'authentik',
              'OAUTH2_DISPLAY_NAME': 'authentik',
              'OAUTH2_CLIENT_ID': "{{ .pgadmin_oauth_client_id }}",
              'OAUTH2_CLIENT_SECRET': "{{ .pgadmin_oauth_client_secret }}",
              'OAUTH2_TOKEN_URL': 'https://auth.${SECRET_DOMAIN}/application/o/token/',
              'OAUTH2_AUTHORIZATION_URL': 'https://auth.${SECRET_DOMAIN}/application/o/authorize/',
              'OAUTH2_USERINFO_ENDPOINT': 'https://auth.${SECRET_DOMAIN}/application/o/userinfo/',
              'OAUTH2_SERVER_METADATA_URL': 'https://auth.${SECRET_DOMAIN}/application/o/pgadmin/.well-known/openid-configuration',
              'OAUTH2_API_BASE_URL': 'https://auth.${SECRET_DOMAIN}/',
              'OAUTH2_SCOPE': 'openid email profile',
              'OAUTH2_BUTTON_COLOR': '#5E93D9',
              'OAUTH2_ICON': 'lock'
          }]
        pgpass: |
          postgres17-rw.database.svc.cluster.local:5432:postgres:postgres:"{{.postgres_super_password }}"
  dataFrom:
    - extract:
        key: pgadmin
    - extract:
        key: cloudnative-pg
