---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: cloudnative-pg-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: POSTGRES_CLOUDNATIVE_SUPER_USER
    - secretKey: password
      remoteRef:
        key: POSTGRES_CLOUDNATIVE_SUPER_PASSWORD
    - secretKey: aws-access-key-id
      remoteRef:
        key: CLOUDFLARE_R2_CLOUDNATIVE_ACCESS_KEY_ID
    - secretKey: aws-secret-access-key
      remoteRef:
        key: CLOUDFLARE_R2_CLOUDNATIVE_ACCESS_KEY_SECRET
    - secretKey: aws-secret-endpoint
      remoteRef:
        key: CLOUDFLARE_R2_CLOUDNATIVE_ENDPOINT
