---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: cloudnative-pg-dashboard 
    files:
<<<<<<< HEAD
      - cloudnative-pg-dashboard.json
=======
      - cloudnative-pg-dashboard .json
>>>>>>> dd8737198c21df35c50847370ef7a01426d0f91d
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    grafana_folder: Database
  labels:
    grafana_dashboard: "true"


