---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: cloudnative-pg-dashboard 
    files:
      - cloudnative-pg-dashboard .json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    grafana_folder: Database
  labels:
    grafana_dashboard: "true"


