---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-system-githun-webhook-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: flux-webhook
        group: external
        url: "https://flux-webhook.${SECRET_DOMAIN}"
        interval: 1m
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[STATUS] == 404"
        alerts:
          - type: pushover
