---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: home-assistant-secret
    template:
      engineVersion: v2
      data:
        HASS_DARKSKY_API_KEY: "{{ .darksky_api_key }}"
        HASS_ECOBEE_API_KEY: "{{ .ecobee_api_key }}"
        HASS_ELEVATION: "{{ .elevation }}"
        HASS_GOOGLE_PROJECT_ID: "{{ .google_project_id }}"
        HASS_GOOGLE_SECURE_DEVICES_PIN: "{{ .google_secure_device_pin }}"
        HASS_LATITUDE: "{{ .latitude }}"
        HASS_LONGITUDE: "{{ .longitude }}"
        HASS_PIRATE_WEATHER_API_KEY: "{{ .pirate_weather_api_key }}"
  dataFrom:
    - extract:
        key: home-assistant
