---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-unifi
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: external-dns-unifi-secret
    template:
      engineVersion: v2
      data:
        EXTERNAL_DNS_UNIFI_USER: "{{ .unifi_admin_user }}"
        EXTERNAL_DNS_UNIFI_PASS: "{{ .unifi_admin_password }}"
        EXTERNAL_DNS_UNIFY_API_KEY: "{{ .unifi_api_key }}"
  dataFrom:
    - extract:
        key: unifi
