---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ferretdb
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: ferretdb-secret
    template:
      engineVersion: v2
      data:
        FERRETDB_POSTGRESQL_URL: "postgres://{{ .ferretdb_db_user }}:{{ .ferretdb_db_password }}@postgres17-rw.database.svc.cluster.local:5432/{{ .ferretdb_db_name }}"
        FERRETDB_TEST_ENABLE_NEW_AUTH: "true"
        FERRETDB_SETUP_USERNAME: "{{ .ferretdb_db_user }}"
        FERRETDB_SETUP_PASSWORD: "{{ .ferretdb_db_password }}"
        FERRETDB_SETUP_DATABASE: ferret

        # Database Initialiation
        INIT_POSTGRES_HOST: "postgres17-rw.database.svc.cluster.local"
        INIT_POSTGRES_DBNAME: "{{ .ferretdb_db_name}}"
        INIT_POSTGRES_USER: "{{ .ferretdb_db_user }}"
        INIT_POSTGRES_PASS: "{{ .ferretdb_db_password }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .postgres_super_password }}"
  dataFrom:
    - extract:
        key: ferretdb
    - extract:
        key: cloudnative-pg
