---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: &app dragonfly-operator
  labels:
    app.kubernetes.io/instance: *app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: *app
