apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:xrsz2ZuP0h9/llxSVizUNXc5VgXNrkbQKdKvwNS8n/U=,iv:oD0g3S3glZjQWRv6JkJxzwSjAOrcfSbiNDiC0DpfvgE=,tag:eSe7Y+YR/13Ky7xP3dJs6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12jenp34w79lv5f4m428dk6h9jxtma4r3teujmg5wmh7p295ryfvqhjykad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRUZzNGJkbFROTjI0cGVT
            QzROcUM2S1FhdjVISXBweExDNm1LK2RUdTBNCjFSZFp2Y1RQZmFYYXpQRGlrTnJl
            a05lN2k4UWp4bDEyRVhZTVBBckpPNG8KLS0tIHg2dEdSZ1p1dENSMFZJckJvV3BO
            MjRhYjNGTWFqd1JTcm41Z1hiUVc4b2cKEz7f9aRjKpGuCSpax3KT7eviEO4ro1bU
            5VfbNxDTOv9+OcdPc3KbtZ1N71MQSpukCmjHbUHu2fNorr4jW5MeyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-08T04:35:03Z"
    mac: ENC[AES256_GCM,data:jyh49f5SzafEoPgqI/jieuW0BWadgiP1uUyX5HoVQsAtrE/kcUs8bed4pMVznJD4i1gUeT0QQQfRizbs4HzD8UxF59D3PGi9l9YfM+rDVe3rVh5EaZR3xynuvBqgHbWV4wAwRCjzEEvXvP+0UU4UlKDyXGEiYmU+0yWH8Ga2Xj4=,iv:HOmkcdfN/HcDQ6CFJo7fAgfgif9f4QCZtRLowb8Znwk=,tag:+OIsjcZuGqOqK/z87fy10A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
