apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:OMzwpySneMMrtw3B6gflf2HAgJ7fNYe3h74udEiJHLA=,iv:QS0G+P5LtSyCHsvTRNbG0HcWPKILWe7CQz/DiI5d6BY=,tag:Qk4VkzZH37/OgfXUA8V1lw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12jenp34w79lv5f4m428dk6h9jxtma4r3teujmg5wmh7p295ryfvqhjykad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQzArOWlGQTRGb0tYb3c5
            Y1pXTHFLckRqdXB4eUx0ZVB2M0piNHhrYzNvCldJZnZmSkRwU0wyaEhDdFNnNU9h
            RTRaWDg0cWM3RTZxUUZ6R1hONXMrMkUKLS0tIGlnWVlXRnNzQWJHM0dob1YxTmc0
            WGc4dXlXSjlmQTVaYll5RkxNaENDTVEKaSWEXp/KnyZg3t4BvbA1o+z9Zz1rAppX
            r/xgurrnXXk4CjsAnrySZyXbDRmh08WSVQWkNTY1CpuazniemGcEpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-08T21:16:17Z"
    mac: ENC[AES256_GCM,data:IydwXhOfeIovX/tklqnpuJ5pd/8rbSY2jkv9Hp0VV00oF1GiaOKH5mIBU2v6QnncwQMOllMt8eKHp4016onQEQLN9GCggr23E3MsYzV5VpadmLobNrTqO6UUDfjIGmQTKu22+rCU4y6XI8ucUk9rQAQ6D+OGagixT6AdFtesblA=,iv:x8l1WVRfYBATd9fOLBsTKlGoUycIwSjTCdL/ZgUv7bw=,tag:BaPv5wbNiudHknvC2fauzw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
