apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:O3AAElY9roK8+JRdgbia8FAarMtMA6KxUp6dHgnPKXo=,iv:cj1M2H+XPGSzRPyF6tLHj7QVIYJvFIlJNbgjXt+hFa0=,tag:mu8w9X6iscIKhDJU+hYblA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12jenp34w79lv5f4m428dk6h9jxtma4r3teujmg5wmh7p295ryfvqhjykad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVmR3NHFBV3E2dmdTVnR2
            Z1pnRFJnWnlUTjNKRVo5Z2tsbk9wRzBDeFhNCjkxWnRwOFprSzFXSXhNUDlKKzQ3
            SkxpM3YyaUtWaXRiQUova2hxWFQ2U2sKLS0tIFNBUmNkRFNwVWptUzFUOTd5Zjlp
            VDk5elVMV20wOXAvaVNxYVgvbnhjbnMK4x8tdTpDWtZyyUQK7Dx73tAHdHy3fY73
            WPzgz9OQZaViPqIIRy6LPd5MZjPeFj5dG/kAyoKZCNM/2okC7pvrZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-08T06:43:58Z"
    mac: ENC[AES256_GCM,data:5RbT28najIvVwtpmlAnzqbKOycwAKWXRdDVOHPT7gvIJAURvgfEr6o2FDz29hUtSZUd2jRqQWHfJLfnNF5gFREIq5ZQ7Pp7Hi58KebFcYk8/UQH4M0nkYksbGaE85rv2j3tlh5GjgOEdm7aNMEUW69ciwVcTcUbAoyxOHlTzpjw=,iv:zhTmlA4RfpdAsuRGiQFz5NqOYDSbIQy7QtRKCrJ7dfY=,tag:s2E1Yb5xWwN5zwt9IUz9SA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
