apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:Dc6q/b/IFoxPWmvqCx6yHzxp5dTwFQPZRIOsFfkhRn8=,iv:0a5vRQDuEsfSv88+jP0sXQtSiGkJp7imaHREHM1c+3o=,tag:+T4oioDG3D5BXyNa5LHQ5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12jenp34w79lv5f4m428dk6h9jxtma4r3teujmg5wmh7p295ryfvqhjykad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUEsrVWpZVDNBVVBudU1M
            ZkRiRllzTzlhbVVkTU9QLzlaZHNHT0Z2TVdRCktzSEZIdVFBREdVa2VUUzBDdFlH
            KzU1TnJnOUlDdDVjZEtyNWFxZlVXeU0KLS0tIEdzS1h0TFJvOWJQbTBwTUVJVzlJ
            TDB1UVRodXI0ZFdnR0JZakdkU2N1dDAKJTZzBFZmS4qNbhdA4vF5AXR3GTtHEAfL
            MK9VpLJdu2HLzODNL/YkaOsDDQY4zyM/7YEU6b0n19p0cdS5O8X9Gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-08T07:21:38Z"
    mac: ENC[AES256_GCM,data:5iCl21TRwYPsJA5ofgETDZt8BcBH3s0OpZHhoCl3F7DRXjalOAw72daz07GZuQXns4hdiVx/UuwtfBOFduUSXI7y3/AgiEXmYhzkrPR/YQ0gQ5ffs33sI2kwVf6MN5KyziN40t9yK/znOP6ca848cqLI+hs6Y91fDCUFjfiRMhY=,iv:7MdpbcVbf04721WrjNXsazBq/jw08RGRUezELlBFDI8=,tag:qUhPdnSEwQhszcXv1y1DZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
