---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: mongodb-secret
    template:
      engineVersion: v2
      data:
        mongodb-root-password: "{{ .mongodb_root_password }}"
        mongodb-root-user: "{{ .mongodb_root_user }}"
  dataFrom:
    - extract:
        key: mongodb
