---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-lb
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "mongodb.${SECRET_DOMAIN}"
    lbipam.cilium.io/ips: 10.10.0.156
spec:
  type: LoadBalancer
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017
      targetPort: mongodb
  selector:
      app.kubernetes.io/component: mongodb
      app.kubernetes.io/instance: mongodb
      app.kubernetes.io/name: mongodb
