---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name homepage-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ## Infrastructure
        HOMEPAGE_VAR_UNIFI_USERNAME: "{{ .unifi_unpoller_user }}"
        HOMEPAGE_VAR_UNIFI_PASSWORD: "{{ .unifi_unpoller_password }}"
        HOMEPAGE_VAR_PROXMOX_HOST_URL: "{{ .proxmox_host_url }}"
        HOMEPAGE_VAR_PROXMOX_TOKEN_ID: "{{ .proxmox_terraform_token_id }}"
        HOMEPAGE_VAR_PROXMOX_PASSWORD: "{{ .proxmox_terraform_token_secret }}"
        HOMEPAGE_VAR_TRUENAS_TOKEN: "{{ .truenas_homepage_apikey }}"

        # HOMEPAGE_VAR_HASS_TOKEN: "{{ .hass_token }}"

        

        ## Security
        # HOMEPAGE_VAR_AUTHENTIK_TOKEN: "{{ .authentik_token }}"

        ## Selfhosted
        # HOMEPAGE_VAR_IMMICH_TOKEN: "{{ .immich_token }}"
        # HOMEPAGE_VAR_AUDIOBOOKSHELF_TOKEN: "{{ .audiobookshelf_token }}"
        # HOMEPAGE_VAR_PAPERLESS_TOKEN: "{{ .paperless_token }}"
        # HOMEPAGE_VAR_NEXTCLOUD_TOKEN: "{{ .nextcloud_token }}"
  dataFrom:
  - extract:
      key: unifi
  - extract:
      key: proxmox
  - extract:
      key: truenas
   