apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant
status:
  phase: Bound
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
  volumeMode: Filesystem
