---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-volsync-minio"
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: "${APP}-volsync-minio-secret"
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "s3:{{ .endpoint_url }}/{{ .restic_repository_template }}/${APP}"
        RESTIC_PASSWORD: "{{ .resitc_password }}"
        AWS_ACCESS_KEY_ID: "{{ .access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secret_access_key }}"
  dataFrom:
    - extract:
        key: minio
    - extract:
        key: volsync-minio-template