---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rook-ceph-mon
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: rook-ceph-mon
    template:
      data:
        admin-secret:  "{{ .rook_ceph_mon_admin-secret }}"
        ceph-secret:  "{{ .rook_ceph_mon_ceph-secret }}"
        ceph-username:  "{{ .rook_ceph_mon_ceph-username }}"
        cluster-name:  "{{ .rook_ceph_mon_cluster-name }}"
        fsid:  "{{ .rook_ceph_mon_fsid }}"
        mon-secret:  "{{ .rook_ceph_mon_mon-secret }}"
  dataFrom:
    - extract:
        key: rook-ceph
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rook-csi-cephfs-node
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: rook-csi-cephfs-node
    template:
      data:
        adminID: "{{ .rook_csi_cephfs_node_adminID }}"
        adminKey: "{{ .rook_csi_cephfs_node_adminKey }}"
  dataFrom:
    - extract:
        key: rook-ceph
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rook-csi-cephfs-provisioner
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: rook-csi-cephfs-provisioner
    template:
      data:
        adminID: "{{ .rook_csi_cephfs_provisioner_adminID }}"
        adminKey: "{{ .rook_csi_cephfs_provisioner_adminKey }}"
  dataFrom:
    - extract:
        key: rook-ceph
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rook-csi-rbd-node
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: rook-csi-rbd-node
    template:
      data:
        adminID: "{{ .rook_csi_rbd_node_adminID }}"
        adminKey: "{{ .rook_csi_rbd_node_adminKey }}"
  dataFrom:
    - extract:
        key: rook-ceph
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rook-csi-rbd-provisioner
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: rook-csi-rbd-provisioner
    template:
      data:
        adminID: "{{ .rook_csi_rbd_provisioner_adminID }}"
        adminKey: "{{ .rook_csi_rbd_provisioner_adminKey }}"
  dataFrom:
    - extract:
        key: rook-ceph
