apiVersion: v1
kind: Secret
metadata:
    name: rook-ceph-mon
stringData:
    admin-secret: ENC[AES256_GCM,data:woJUCWMGFfC7VEZb,iv:95fKbNISgMwUzMDiWKq7F3od6MFhTJAdFjQ3FxV8HX0=,tag:F2x3DJgUocjKpPMfYkSzMQ==,type:str]
    ceph-secret: ENC[AES256_GCM,data:FxBmR40UuLw+LYBjyBqhCVeH493YAI/4dPoJfXLW65CmMemEuOA50g==,iv:gh0VvHzU29+WJ95ahmNDiFAU8ikQL+xLRb3crO/twWI=,tag:o6n+sZA3Df/VOSMwD7Rfyg==,type:str]
    ceph-username: ENC[AES256_GCM,data:giM5HiivlFEFIDB6u6QV/zWfjEw=,iv:RNzHDUAH9Y8RCKJbt2szgNdgxYLtcErs8GWPsB9bWJc=,tag:+iRKcERKGb8X78QZFup73Q==,type:str]
    cluster-name: ENC[AES256_GCM,data:EBQ0J3DKcAKprU5Wmj52ssZp,iv:aGHwVF63B/tOTU6kj2Z3I9Jpwu/GPApflFdR3iwdYog=,tag:rDwL2YIcAVYHIJrm7Hh1AQ==,type:str]
    fsid: ENC[AES256_GCM,data:uPpFRM45HaKuKV1qhSrgoXyjDy4WDvFdLbo7RgD4H/Ue+Zl1,iv:e1Baqkzvty2d84QRQJczHlCQJOSThn0/j1qs5HyvG7k=,tag:KYAaSlNMML9yEIQnRd8rXQ==,type:str]
    mon-secret: ENC[AES256_GCM,data:7HYsI7V4SzSKfA==,iv:C6O81SEjIkDlls5xI9oGrTw9cX8fbc/lqYdkAO8JGhs=,tag:i4Wq34XuC2ZEpOsOYSjBDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12jenp34w79lv5f4m428dk6h9jxtma4r3teujmg5wmh7p295ryfvqhjykad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyR2c2aDNVdnh4Rld0SGtU
            cjhYU3k2elhGcWwyQnF4SlpHby9WeWRtdlNVCjMxL0IwWnp1U2RiNWw2a3lzT3Y5
            R09PazBiRTVoV0VOWjRJU1o1elZDY3cKLS0tIEo3QzN1bEpjUkRjWEJpWUJMT1Vo
            RXpsbWVOazNNLzN3TDU3OVl0YTgrTFUKNhipkuiLKvuUPbAC/Aro2cMtyveMg1QO
            EreCkTzDDfX6T8GOeXtYGKq3aHYZI7Q6GCTLNccujNkKzdnitmH9gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-12T02:29:13Z"
    mac: ENC[AES256_GCM,data:WVBSWx5PxB2VrIgYoXgBy5+28ptB3NWCShRAzFVQXSy0Nsgax6RsOADWmA7KddT2qt0LOttcBHI7mGs2+if0W6m4u1v8dMsnFc98mPM/KdN30U2sejsUJhFfaxIMvZDRT8zxKSGZy8D5kz6BuX7tU1tonKunAFPf3m5by0j6bkU=,iv:BAtGI6+J7KfrJpnm+i+iGtyFbZ8wvj9r6z2nde/CYoc=,tag:O5a/1bkfszpnYJ4BD6WwIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: rook-csi-cephfs-node
stringData:
    adminID: ENC[AES256_GCM,data:pBnd53CyXgqZH78uvJkE,iv:oEvx5mGGuJLBx8P+uwC5Qg8VkAmmctEJwW9ws9GVLOk=,tag:7sZSwbut+uiB9k2mAbusNw==,type:str]
    adminKey: ENC[AES256_GCM,data:JVW0yoJ/KXhIE2psPn6yT7hnLG2KP5DXb8bCTZIKNOuQv3CVYONR5QLk,iv:FZpvYfMFszLuNgIFNDuTAEhB5km56AgUNh9O9Ak3Dx4=,tag:WZebHxwjZbuFcrlaDpdivA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12jenp34w79lv5f4m428dk6h9jxtma4r3teujmg5wmh7p295ryfvqhjykad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyR2c2aDNVdnh4Rld0SGtU
            cjhYU3k2elhGcWwyQnF4SlpHby9WeWRtdlNVCjMxL0IwWnp1U2RiNWw2a3lzT3Y5
            R09PazBiRTVoV0VOWjRJU1o1elZDY3cKLS0tIEo3QzN1bEpjUkRjWEJpWUJMT1Vo
            RXpsbWVOazNNLzN3TDU3OVl0YTgrTFUKNhipkuiLKvuUPbAC/Aro2cMtyveMg1QO
            EreCkTzDDfX6T8GOeXtYGKq3aHYZI7Q6GCTLNccujNkKzdnitmH9gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-12T02:29:13Z"
    mac: ENC[AES256_GCM,data:WVBSWx5PxB2VrIgYoXgBy5+28ptB3NWCShRAzFVQXSy0Nsgax6RsOADWmA7KddT2qt0LOttcBHI7mGs2+if0W6m4u1v8dMsnFc98mPM/KdN30U2sejsUJhFfaxIMvZDRT8zxKSGZy8D5kz6BuX7tU1tonKunAFPf3m5by0j6bkU=,iv:BAtGI6+J7KfrJpnm+i+iGtyFbZ8wvj9r6z2nde/CYoc=,tag:O5a/1bkfszpnYJ4BD6WwIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
metadata:
    name: rook-csi-cephfs-provisioner
stringData:
    adminID: ENC[AES256_GCM,data:yMxTOKwA5J3HnfUM9ujZl0XSGbIjsA==,iv:LkFfi46OZBvhdJbSrkYZeW9Xx5AfsbQJYD93OpPtqJc=,tag:STPICjShW5DN3vgw/JuS+g==,type:str]
    adminKey: ENC[AES256_GCM,data:DqyaII99eScaomOxud35PhytHkq4U+ETq567nX0eSR2CbwDdqq2lxA==,iv:v0bcoBDWIQ3pdM7cjRQ9FCCd0Da3JGn1bv/BtpjQ6Ag=,tag:7f579iFbgO1M+wYv/I5cxw==,type:str]
kind: Secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12jenp34w79lv5f4m428dk6h9jxtma4r3teujmg5wmh7p295ryfvqhjykad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyR2c2aDNVdnh4Rld0SGtU
            cjhYU3k2elhGcWwyQnF4SlpHby9WeWRtdlNVCjMxL0IwWnp1U2RiNWw2a3lzT3Y5
            R09PazBiRTVoV0VOWjRJU1o1elZDY3cKLS0tIEo3QzN1bEpjUkRjWEJpWUJMT1Vo
            RXpsbWVOazNNLzN3TDU3OVl0YTgrTFUKNhipkuiLKvuUPbAC/Aro2cMtyveMg1QO
            EreCkTzDDfX6T8GOeXtYGKq3aHYZI7Q6GCTLNccujNkKzdnitmH9gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-12T02:29:13Z"
    mac: ENC[AES256_GCM,data:WVBSWx5PxB2VrIgYoXgBy5+28ptB3NWCShRAzFVQXSy0Nsgax6RsOADWmA7KddT2qt0LOttcBHI7mGs2+if0W6m4u1v8dMsnFc98mPM/KdN30U2sejsUJhFfaxIMvZDRT8zxKSGZy8D5kz6BuX7tU1tonKunAFPf3m5by0j6bkU=,iv:BAtGI6+J7KfrJpnm+i+iGtyFbZ8wvj9r6z2nde/CYoc=,tag:O5a/1bkfszpnYJ4BD6WwIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: rook-csi-rbd-node
stringData:
    userID: ENC[AES256_GCM,data:A6uPom3lvw80upfd,iv:lsjrirEA+wetvDjX6aNlJVjFEJw+o1eIhJfj41iwIjQ=,tag:cAXuHjICZX0d6i6RxcmcLg==,type:str]
    userKey: ENC[AES256_GCM,data:O7AG90VXG/4XIO2f7B/82Kc1SwXwO6m41Cp18vByeJ3URmn0JNx1Pw==,iv:eksNKxyFhcj2H0+fs5+flTborS7P2dhd8HBXNf44ijM=,tag:fthBoPyIVuRF7lJNPczI7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12jenp34w79lv5f4m428dk6h9jxtma4r3teujmg5wmh7p295ryfvqhjykad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyR2c2aDNVdnh4Rld0SGtU
            cjhYU3k2elhGcWwyQnF4SlpHby9WeWRtdlNVCjMxL0IwWnp1U2RiNWw2a3lzT3Y5
            R09PazBiRTVoV0VOWjRJU1o1elZDY3cKLS0tIEo3QzN1bEpjUkRjWEJpWUJMT1Vo
            RXpsbWVOazNNLzN3TDU3OVl0YTgrTFUKNhipkuiLKvuUPbAC/Aro2cMtyveMg1QO
            EreCkTzDDfX6T8GOeXtYGKq3aHYZI7Q6GCTLNccujNkKzdnitmH9gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-12T02:29:13Z"
    mac: ENC[AES256_GCM,data:WVBSWx5PxB2VrIgYoXgBy5+28ptB3NWCShRAzFVQXSy0Nsgax6RsOADWmA7KddT2qt0LOttcBHI7mGs2+if0W6m4u1v8dMsnFc98mPM/KdN30U2sejsUJhFfaxIMvZDRT8zxKSGZy8D5kz6BuX7tU1tonKunAFPf3m5by0j6bkU=,iv:BAtGI6+J7KfrJpnm+i+iGtyFbZ8wvj9r6z2nde/CYoc=,tag:O5a/1bkfszpnYJ4BD6WwIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: rook-csi-rbd-provisioner
stringData:
    userID: ENC[AES256_GCM,data:HZAinmo33ORd1oiPcRTfpo+m7TL9hRtn,iv:c+wdF4BpQQs7B+mN4iNeKF8CfjD/upuEB4K7bE4OvDA=,tag:j9DQZgskEc9bf8cf9q5crg==,type:str]
    userKey: ENC[AES256_GCM,data:Orxi9qyKvJxDSFcwXcZB4IGnjrylMrwlJrBi3CTQguiH0GozOvtPag==,iv:34ZuplI/Yf0IrL+AvLcaQa7bb/yWWTFzHKmb22061QY=,tag:BaErhC424oT8TUEgdWKMKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12jenp34w79lv5f4m428dk6h9jxtma4r3teujmg5wmh7p295ryfvqhjykad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyR2c2aDNVdnh4Rld0SGtU
            cjhYU3k2elhGcWwyQnF4SlpHby9WeWRtdlNVCjMxL0IwWnp1U2RiNWw2a3lzT3Y5
            R09PazBiRTVoV0VOWjRJU1o1elZDY3cKLS0tIEo3QzN1bEpjUkRjWEJpWUJMT1Vo
            RXpsbWVOazNNLzN3TDU3OVl0YTgrTFUKNhipkuiLKvuUPbAC/Aro2cMtyveMg1QO
            EreCkTzDDfX6T8GOeXtYGKq3aHYZI7Q6GCTLNccujNkKzdnitmH9gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-12T02:29:13Z"
    mac: ENC[AES256_GCM,data:WVBSWx5PxB2VrIgYoXgBy5+28ptB3NWCShRAzFVQXSy0Nsgax6RsOADWmA7KddT2qt0LOttcBHI7mGs2+if0W6m4u1v8dMsnFc98mPM/KdN30U2sejsUJhFfaxIMvZDRT8zxKSGZy8D5kz6BuX7tU1tonKunAFPf3m5by0j6bkU=,iv:BAtGI6+J7KfrJpnm+i+iGtyFbZ8wvj9r6z2nde/CYoc=,tag:O5a/1bkfszpnYJ4BD6WwIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
