apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: documents-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cephfs-sklab-retain
  resources:
    requests:
      storage: 100Gi
