apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:5r9ZNlRIQSY4b2FXfDxm47kJ5cPgE64otSriSw5oHA5eNHpk70mc2A==,iv:kchSoTHr33Xeoz3DbncgY6MJ7fsZwYyyQ5GImQV8NbI=,tag:NuOgyTvfEosLLCrN4Y6oYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12jenp34w79lv5f4m428dk6h9jxtma4r3teujmg5wmh7p295ryfvqhjykad
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkaFhGZXFUMXpKSk5TbG5H
            ZDdlTlpDQm85bFRPR2JwYzFZVUZHTTcxSzBBCnZWSW1lQmVSdXNXZzBIb2I4VzJ5
            dm44SllNbVRKV1dXUDUxcHlCMTljN3cKLS0tIGJWYmUrZVliU1ZPbjVqMXMwQWZK
            T2U2SEd1Z2dydFZyZVRGNzNnWFJoQXcKKgVI9ccV0qim+wSOJ4295LdLTAXkJ7Mc
            C9pL9YXiddn7N/jx09vujo2jXmnGhR0K9OS85r2UN3kruKPUxA/cjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-08T19:53:58Z"
    mac: ENC[AES256_GCM,data:tYZHIO2WxQVSy/yJMd0JNEHFEdAp896hpYvcE5SwPyHMVaAkM6+nEORUrIlFjM6pWTfm+J8Ow1r08xvLYiXrvO1lcvoYKIyXlRf6cm7jVMmMpcKu7jlma0skESfjB5LNe00IKeRVbKbtHusiIU6b78i8jkeohpjankPxvacAhlg=,iv:f9K4Skw+EpClkccb8A48NpKV/8DR2RKu7GUUDRHfHT0=,tag:8z+HzZHOwuRzExVGm0Rv0g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
