---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname calibre-web
  namespace: flux-system
spec:
  targetNamespace: media
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 30m
  timeout: 5m
  path: "./kubernetes/apps/media/calibre-web/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  dependsOn:
    - name: external-secrets-stores
    - name: csi-driver-nfs
    - name: rook-ceph-cluster
    - name: cloudnative-pg-cluster
    - name: volsync
  postBuild:
    substitute:
      APP: *appname
      HOSTNAME: calibre-web.${SECRET_DOMAIN}
      VOLSYNC_CLAIM: calibre-web-config
      GATUS_SUBDOMAIN: media

      VOLSYNC_CAPACITY: 1Gi
      VOLSYNC_CACHE_CAPACITY: 1Gi
      VOLSYNC_STORAGECLASS: ceph-block
      VOLSYNC_SNAPSHOTCLASS: csi-ceph-blockpool