---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app linkwarden
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: authentik
      namespace: security
  values:
    defaultPodOptions:
      automountServiceAccountToken: false

    controllers:
      main:

        annotations:
          reloader.stakater.com/auto: "true"
          
        initContainers:
          - name: init-db
            image: ghcr.io/onedr0p/postgres-init:16.6
            envFrom:
              - secretRef:
                  name: linkwarden-init-secret

        containers:
          main:
            image:
              repository: ghcr.io/linkwarden/linkwarden
              tag: v2.8.4
            resources:
              requests:
                memory: 512Mi
              limits:
                memory: 600Mi
            env:
              NEXTAUTH_URL: https://${HOSTNAME}/api/v1/auth
              STORAGE_FOLDER: "config" # Will always end up as /data/STOREAGE_FOLDER so eg /data/config
              NEXT_PUBLIC_AUTHENTIK_ENABLED: "true"
              HOME: /data/config
            envFrom:
              - secretRef:
                  name: linkwarden-secret
    service:
      main:
        ports:
          http:
            port: 3000
    ingress:
      main:
        className: external
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /data/config
      next-cache:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /data/.next/cache

