{
 "title": "Restic Rest Server",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(rest_server_blob_read_total,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(process_start_time_seconds{job=\"$job\"},instance)"
    }
   },
   { "name": "group", "label": "Group By", "query": "type,repo,user" }
  ]
 },
 "panels": [
  {
   "title": "Blob Write Throughput by $group",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rest_server_blob_write_bytes_total) by ($group)",
     "legendFormat": "{{$group}}"
    }
   ]
  },
  {
   "title": "Blob Write Operations by $group",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(rest_server_blob_write_total{instance=\"$instance\"}[60s])) by ($group)",
     "legendFormat": "{{$group}}"
    }
   ]
  },
  {
   "title": "Blob Read Throughput by $group",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(rest_server_blob_read_bytes_total{instance=\"$instance\"}[60s])) by ($group)",
     "legendFormat": "{{$group}}"
    }
   ]
  },
  {
   "title": "Blob Read Operations by $group",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(rest_server_blob_read_total{instance=\"$instance\"}[60s])) by ($group)",
     "legendFormat": "{{$group}}"
    }
   ]
  },
  {
   "title": "Blob Delete Throughput by $group",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(rest_server_blob_delete_bytes_total{instance=\"$instance\"}[60s])) by ($group)",
     "legendFormat": "{{$group}}"
    }
   ]
  },
  {
   "title": "Blob Delete Operations by $group",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(rest_server_blob_delete_total{instance=\"$instance\"}[60s])) by ($group)",
     "legendFormat": "{{$group}}"
    }
   ]
  }
 ]
}