---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name merge-explorer-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MERGE_WALLET_RPC_USER: "{{ .merge_wallet_rpc_user }}"
        MERGE_WALLET_RPC_PASSWORD: "{{ .merge_wallet_rpc_password }}"

  dataFrom:
  - extract:
      key: block-explorer-merge

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: merge-explorer-ghcr-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: merge-explorer-ghcr-secret
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{"auths":{"ghcr.io":{"auth":"{{ ( printf "%s:%s" .github_repo_read_username .github_repo_read_token ) | b64enc }}"}}}'
  dataFrom:
  - extract:
      key: github